/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Shared mock data for Prometheus metrics, labels, and label values.
 *
 * Extracted from `public/components/promql_editor.tsx` so that both the
 * PromQL editor (public/) and the mock backend (common/) can reference the
 * same data without a `common -> public` dependency.
 */

export const MOCK_METRICS: readonly string[] = [
  'node_cpu_seconds_total',
  'node_memory_MemTotal_bytes',
  'node_memory_MemAvailable_bytes',
  'node_memory_MemFree_bytes',
  'node_filesystem_avail_bytes',
  'node_filesystem_size_bytes',
  'node_disk_read_bytes_total',
  'node_disk_written_bytes_total',
  'node_network_receive_bytes_total',
  'node_network_transmit_bytes_total',
  'node_network_receive_drop_total',
  'node_load1',
  'node_load5',
  'node_load15',
  'http_requests_total',
  'http_request_duration_seconds_bucket',
  'http_request_duration_seconds_sum',
  'http_request_duration_seconds_count',
  'http_request_size_bytes',
  'http_response_size_bytes',
  'up',
  'scrape_duration_seconds',
  'scrape_samples_scraped',
  'process_cpu_seconds_total',
  'process_resident_memory_bytes',
  'process_open_fds',
  'go_goroutines',
  'go_gc_duration_seconds',
  'go_memstats_alloc_bytes',
  'kube_pod_container_status_restarts_total',
  'kube_pod_status_phase',
  'kube_deployment_status_replicas',
  'kube_node_status_condition',
  'kube_pod_container_resource_limits',
  'kube_pod_container_resource_requests',
  'db_connection_pool_available',
  'db_connection_pool_total',
  'db_query_duration_seconds',
  'probe_ssl_earliest_cert_expiry',
  'probe_http_duration_seconds',
  'probe_success',
  'container_cpu_usage_seconds_total',
  'container_memory_usage_bytes',
  'container_network_receive_bytes_total',
] as const;

export const MOCK_LABEL_NAMES: readonly string[] = [
  'instance',
  'job',
  'mode',
  'cpu',
  'device',
  'mountpoint',
  'fstype',
  'severity',
  'alertname',
  'team',
  'service',
  'environment',
  'region',
  'namespace',
  'pod',
  'container',
  'node',
  'le',
  'quantile',
  'method',
  'status',
  'handler',
  'code',
  'application',
  'status_code',
  'grpc_code',
  'grpc_service',
  'grpc_method',
  'endpoint',
  'peer_service',
] as const;

export const MOCK_LABEL_VALUES: Readonly<Record<string, readonly string[]>> = {
  instance: ['i-0abc123:9100', 'i-0def456:9100', 'i-0ghi789:9100', 'api-gateway:8080'],
  job: ['node-exporter', 'prometheus', 'api-gateway', 'kubernetes', 'blackbox-exporter'],
  mode: ['idle', 'user', 'system', 'iowait', 'nice', 'irq', 'softirq', 'steal'],
  severity: ['critical', 'warning', 'info'],
  team: ['infra', 'platform', 'sre', 'security', 'data', 'network'],
  service: ['node-exporter', 'api-gateway', 'kubernetes', 'postgres', 'blackbox-exporter'],
  environment: ['production', 'staging', 'development'],
  region: ['us-east-1', 'us-west-2', 'eu-west-1', 'ap-southeast-1'],
  namespace: ['production', 'staging', 'kube-system', 'monitoring'],
  method: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH'],
  status: ['200', '201', '301', '400', '401', '403', '404', '500', '502', '503'],
  application: ['checkout', 'platform', 'user-service', 'order-service', 'observability'],
  status_code: ['200', '201', '301', '400', '401', '403', '404', '500', '502', '503'],
  grpc_code: [
    'OK',
    'CANCELLED',
    'UNKNOWN',
    'INVALID_ARGUMENT',
    'DEADLINE_EXCEEDED',
    'NOT_FOUND',
    'ALREADY_EXISTS',
    'PERMISSION_DENIED',
    'RESOURCE_EXHAUSTED',
    'FAILED_PRECONDITION',
    'ABORTED',
    'OUT_OF_RANGE',
    'UNIMPLEMENTED',
    'INTERNAL',
    'UNAVAILABLE',
    'DATA_LOSS',
    'UNAUTHENTICATED',
  ],
  grpc_service: [
    'user.UserService',
    'order.OrderService',
    'payment.PaymentService',
    'inventory.InventoryService',
  ],
  grpc_method: ['GetUser', 'CreateOrder', 'ProcessPayment', 'CheckInventory', 'ListItems'],
  endpoint: ['/', '/api/health', '/api/users', '/api/orders', '/api/payments', '/api/inventory'],
  peer_service: ['payment-api', 'order-api', 'user-api', 'inventory-api', 'notification-api'],
} as const;
