/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/// <reference types="cypress" />

/*
 * SLO rule-adoption Phase 4 W4.11 end-to-end.
 *
 * Run locally with:
 *   yarn cypress:run --spec \
 *     .cypress/integration/slo_test/adoption.spec.js
 *
 * Requires the observability-stack dev cluster (Cortex-backed `prometheus`
 * container + a DirectQuery datasource named by `sloDatasourceId`) and the
 * feature flags `observability.slo.ruleDedup.enabled` /
 * `observability.slo.ruleAdoption.enabled` set to true. When either flag is
 * off the server returns 412 on `/_orphans`; the spec detects that in a
 * `before` hook and skips every `it()` so CI stays green regardless of the
 * runtime config.
 *
 * Scenarios (Session B — Item 3 reconciliation with Batch 3 UI):
 *
 *   1. Lost-SO recovery — create an SLO, backdoor-delete the saved object
 *      so the rule group is "owner-less", open the Adoption page, click
 *      Recover, and assert the SLO reappears on the listing.
 *   2. Tamper — backdoor-delete the SO and then tamper with the recording
 *      group via the ruler admin API. Detector reclassifies the orphan as
 *      drift (`specIntegrity: 'mismatch'`) and it lands in the unknowns
 *      accordion; Recover is never offered.
 *   3. Unsupported-schema (Session B Item 1) — seed a group directly on the
 *      ruler with a bumped provenance schemaVersion. The unknowns row
 *      surfaces the schema-unknown copy so operators can distinguish
 *      "upgrade plugin" from "legacy layout".
 *   4. No-external-vendor DOM assertion — explicit check that the external
 *      dashboards vendor is not named on the adoption page.
 *
 * Batch 3 shipped the Recover page only — there is no Clone tab. Cross-
 * datasource clone is covered by the service-layer integration test
 * (`phase4_adoption_integration.test.ts`) and doesn't need a Cypress arm.
 *
 * Backdoor-delete path: the plugin does not expose a test-only hook that
 * removes the SLO saved object without also tearing down the ruler-side
 * rule group, which is exactly the precondition the adoption surface needs.
 * We therefore delete the saved object directly through the core
 * `/api/saved_objects/<type>/<id>` endpoint with the `osd-xsrf` header;
 * this leaves the ruler rule group behind, re-creating the orphan state
 * the reconciler surfaces via `_orphans`.
 */

const SLO_BASE = '/api/observability/v1/slos';
const SAVED_OBJECTS_BASE = '/api/saved_objects';
// Saved-object type used by the SLO plugin. Kept in sync with
// server/saved_objects/slo_definition.ts; if the SO type rename lands the
// adoption spec needs an update too. Tracked in the plan.
const SLO_SO_TYPE = 'slo-definition';
const APP_ID = 'observability-apm-slo';
// Cortex / Prometheus-compatible ruler admin root (see the plugin CLAUDE.md —
// "SLO ruler dual-write against Cortex" section). Ruler admin is unprefixed.
const RULER_ROOT = Cypress.env('rulerRoot') || 'http://localhost:9090';

const randomId = (prefix) =>
  `${prefix}-${Math.random().toString(36).slice(2, 8)}-${Date.now().toString(36)}`;

// ---------------------------------------------------------------------------
// Fixture builders — inlined per workstream rules (no shared helpers touched)
// ---------------------------------------------------------------------------

function buildMinimalSloSpec(datasourceId, name) {
  return {
    datasourceId,
    name,
    description: 'Cypress adoption spec — autogenerated',
    enabled: true,
    mode: 'active',
    service: 'cypress-svc',
    owner: { teams: ['cypress-team'] },
    sli: {
      type: 'single',
      definition: {
        backend: 'prometheus',
        type: 'availability',
        calcMethod: 'events',
        metric: 'http_requests_total',
        goodEventsFilter: 'status_code!~"5.."',
      },
      dimensions: [{ name: 'service', value: 'cypress-svc' }],
    },
    objectives: [{ name: 'primary', target: 0.99 }],
    budgetWarningThresholds: [],
    window: { type: 'rolling', duration: '28d' },
    alerting: {
      strategy: 'mwmbr',
      burnRates: [
        {
          shortWindow: '5m',
          longWindow: '1h',
          burnRateMultiplier: 14.4,
          severity: 'critical',
          createAlarm: true,
          forDuration: '2m',
        },
      ],
    },
    alarms: {
      sliHealth: { enabled: false },
      attainmentBreach: { enabled: false },
      budgetWarning: { enabled: true },
      noData: { enabled: false, forDuration: '10m' },
      resolved: { enabled: false },
    },
    exclusionWindows: [],
    labels: {},
    annotations: {},
  };
}

/** Create an SLO via the plugin API. Yields the resolved id (or null on failure). */
function createSlo(datasourceId, name) {
  return cy
    .request({
      method: 'POST',
      url: SLO_BASE,
      headers: { 'osd-xsrf': 'true' },
      body: { spec: buildMinimalSloSpec(datasourceId, name) },
      failOnStatusCode: false,
    })
    .then((resp) => {
      if (resp.status === 200 || resp.status === 201) {
        return {
          id: resp.body.id,
          provisioning: (resp.body.status && resp.body.status.provisioning) || null,
        };
      }
      return { id: null, provisioning: null };
    });
}

/** Delete an SLO via the plugin API (tears down the rule group too). */
function deleteSlo(sloId) {
  if (!sloId) return;
  cy.request({
    method: 'DELETE',
    url: `${SLO_BASE}/${encodeURIComponent(sloId)}`,
    headers: { 'osd-xsrf': 'true' },
    failOnStatusCode: false,
  });
}

/**
 * Backdoor-delete the SLO saved object directly through the core SO REST
 * surface. Leaves the ruler rule group in place so the reconciler surfaces
 * it as an adoptable orphan.
 */
function backdoorDeleteSo(sloId) {
  cy.request({
    method: 'DELETE',
    url: `${SAVED_OBJECTS_BASE}/${SLO_SO_TYPE}/${encodeURIComponent(sloId)}`,
    headers: { 'osd-xsrf': 'true' },
    qs: { force: true },
    failOnStatusCode: false,
  });
}

/**
 * Tamper with the recording group by issuing a DELETE via the ruler admin
 * API. The reconciler's detector notices the alert group still carries
 * provenance but the fingerprint-matched recording group is missing — it
 * classifies the orphan as `specIntegrity: 'mismatch'` and routes it to the
 * unknowns accordion. The resulting row never exposes a Recover button.
 *
 * `provisioning.recordingFingerprints` carries one fingerprint per objective.
 * We tamper with the first one — enough to flip integrity for this spec.
 */
function tamperRecordingGroup(provisioning) {
  if (
    !provisioning ||
    !provisioning.rulerNamespace ||
    !provisioning.recordingFingerprints
  ) {
    return;
  }
  const fp = Object.values(provisioning.recordingFingerprints)[0];
  if (!fp) return;
  cy.request({
    method: 'DELETE',
    url: `${RULER_ROOT}/api/v1/rules/${encodeURIComponent(
      provisioning.rulerNamespace
    )}/${encodeURIComponent(`slo:rec:${fp}`)}`,
    failOnStatusCode: false,
  });
}

/**
 * Seed a synthetic alert rule group on the ruler whose `osd_slo_provenance`
 * annotation carries a schemaVersion this plugin doesn't recognize. Exercises
 * the Session B Item 1 path — reconciler reports the orphan as
 * `specIntegrity: 'unsupported_schema'` with `sourceSloId` + `schemaVersion`
 * populated, and the unknowns table renders the "upgrade plugin" copy.
 *
 * The synthetic group carries a single always-firing-false alert rule with
 * the annotation on it. That's enough for the provenance scanner — the spec
 * hash doesn't need to verify (schemaVersion check short-circuits first).
 */
function seedUnsupportedSchemaOrphan(datasourceId, sloId) {
  const namespace = `slo-generated-${datasourceId}`;
  const groupName = `slo:alerts:${sloId}_future`;
  const provenance = {
    schemaVersion: 999,
    pluginVersion: 'cypress-future-99.9.9',
    sloId,
    workspaceId: datasourceId,
    datasourceId,
    createdAt: '2099-01-01T00:00:00Z',
    updatedAt: '2099-01-01T00:00:00Z',
    specSha256: '0'.repeat(64),
    spec: { note: 'unsupported-schema fixture' },
  };
  const groupYaml = [
    `name: ${groupName}`,
    `interval: 60s`,
    `rules:`,
    `  - alert: CypressFutureProvenanceSentinel`,
    `    expr: vector(0) > 1`,
    `    for: 5m`,
    `    labels:`,
    `      slo_id: ${sloId}`,
    `      slo_alarm_type: sentinel`,
    `    annotations:`,
    `      osd_slo_provenance: '${JSON.stringify(provenance).replace(/'/g, "''")}'`,
    `      summary: "future-schema provenance"`,
  ].join('\n');
  cy.request({
    method: 'POST',
    url: `${RULER_ROOT}/api/v1/rules/${encodeURIComponent(namespace)}`,
    headers: { 'Content-Type': 'application/yaml' },
    body: groupYaml,
    failOnStatusCode: false,
  });
  return { namespace, groupName };
}

function removeRulerGroup(namespace, groupName) {
  if (!namespace || !groupName) return;
  cy.request({
    method: 'DELETE',
    url: `${RULER_ROOT}/api/v1/rules/${encodeURIComponent(namespace)}/${encodeURIComponent(
      groupName
    )}`,
    failOnStatusCode: false,
  });
}

// ---------------------------------------------------------------------------
// Spec
// ---------------------------------------------------------------------------

describe('SLO rule adoption — Phase 4 W4.11', () => {
  const datasourceId = Cypress.env('sloDatasourceId') || 'prom_integ_test';

  // Per-it trackers so the after hook can mop up whatever each scenario
  // landed, regardless of where it bailed.
  let lostSloId = null;
  let tamperSloId = null;
  let unsupportedSchemaSloId = null;
  let unsupportedSchemaGroup = null;
  // Whether the server has the adoption feature flags on. Set in the before
  // hook; used by every it() to decide whether to skip.
  let adoptionEnabled = false;

  before(function () {
    // Feature-flag gate. If the server returns 412 the flags are off in this
    // environment; skip the whole describe rather than fail CI.
    cy.request({
      method: 'GET',
      url: `${SLO_BASE}/_orphans`,
      headers: { 'osd-xsrf': 'true' },
      failOnStatusCode: false,
    }).then((res) => {
      if (res.status === 412) {
        cy.log('Adoption feature flags disabled — skipping adoption.spec.js');
        adoptionEnabled = false;
      } else {
        adoptionEnabled = true;
      }
    });
  });

  after(() => {
    // Cleanup — best-effort. Each delete is idempotent and never fails the run.
    [lostSloId, tamperSloId].filter(Boolean).forEach((id) => deleteSlo(id));
    if (unsupportedSchemaGroup) {
      removeRulerGroup(unsupportedSchemaGroup.namespace, unsupportedSchemaGroup.groupName);
    }
  });

  it('recovers a lost SLO via the adoption admin page', function () {
    if (!adoptionEnabled) {
      this.skip();
      return;
    }

    const name = randomId('adoption-lost-1');
    createSlo(datasourceId, name).then(({ id, provisioning }) => {
      expect(id, 'SLO create returned an id').to.be.a('string');
      lostSloId = id;

      // Sanity: the ruler side created the alert + recording groups. Only
      // assert when the provisioning block is Prometheus-backed; other
      // backends would simply skip the ruler step.
      if (provisioning && provisioning.backend === 'prometheus') {
        expect(provisioning.rulerNamespace, 'rulerNamespace').to.be.a('string');
      }

      // Backdoor-delete the SO so the rule group is orphaned.
      backdoorDeleteSo(id);

      // Navigate to the adoption page. Batch 3 ships a single page shell
      // that renders the Recover table directly; there's no tab router.
      cy.visit(`/app/${APP_ID}#/slos/adoption`);
      cy.get('[data-test-subj="sloAdoption-page"]', { timeout: 30000 }).should('be.visible');

      // Adoptable row: each candidate carries a name-text cell keyed on
      // sloId, and an integrity badge carrying the `ok` suffix. The recover
      // button is the actionable anchor.
      cy.get(`[data-test-subj="sloAdoption-recoverTab-name-${id}"]`, {
        timeout: 30000,
      }).should('be.visible');
      cy.get(`[data-test-subj="sloAdoption-integrityBadge-ok-${id}"]`).should('be.visible');

      cy.get(`[data-test-subj="sloAdoption-recoverTab-recoverButton-${id}"]`)
        .should('not.be.disabled')
        .click();

      // EUI success toast — Batch 3's copy is "SLO recovered".
      cy.get('.euiToast--success', { timeout: 20000 })
        .should('be.visible')
        .and('contain.text', 'SLO recovered');

      // Back to listing — the recovered SLO should render with a non-missing
      // rule-health badge.
      cy.visit(`/app/${APP_ID}#/slos`);
      cy.get('[data-test-subj="slosPage"]', { timeout: 30000 }).should('be.visible');
      cy.get(`[data-test-subj="slosRulesBadge-${id}"]`, { timeout: 30000 })
        .should('have.attr', 'data-test-rule-state')
        .and('not.equal', 'missing');
    });
  });

  it('surfaces a tampered orphan in the unknowns accordion and never offers Recover', function () {
    if (!adoptionEnabled) {
      this.skip();
      return;
    }

    const name = randomId('adoption-tamper-1');
    createSlo(datasourceId, name).then(({ id, provisioning }) => {
      expect(id, 'SLO create returned an id').to.be.a('string');
      tamperSloId = id;

      // Step 1 — orphan the saved object.
      backdoorDeleteSo(id);
      // Step 2 — tamper with the recording group so the fingerprint-coverage
      // check fails. Detector routes this as `specIntegrity: 'mismatch'`,
      // which lands in the unknowns bucket (not the candidates table) — the
      // Recover table only renders `specIntegrity === 'ok'` rows.
      tamperRecordingGroup(provisioning);

      cy.visit(`/app/${APP_ID}#/slos/adoption`);
      cy.get('[data-test-subj="sloAdoption-page"]', { timeout: 30000 }).should('be.visible');

      // No Recover action for this sloId — drift is not adoptable.
      cy.get(`[data-test-subj="sloAdoption-recoverTab-recoverButton-${id}"]`).should('not.exist');

      // Unknowns accordion shows the row. The server-side detector populates
      // a `diagnostic` mentioning the missing recording group; the table
      // surfaces the diagnostic copy verbatim.
      cy.get('[data-test-subj="sloAdoption-recoverTab-unknownsAccordion"]', {
        timeout: 30000,
      })
        .should('be.visible')
        .click();

      cy.get('[data-test-subj="sloAdoption-recoverTab-unknownsTable"]')
        .should('be.visible')
        .invoke('text')
        .then((text) => {
          expect(text.toLowerCase()).to.match(/missing recording group|drift|mismatch/);
        });
    });
  });

  it('surfaces unsupported-schema orphans with the "upgrade plugin" copy (Session B Item 1)', function () {
    if (!adoptionEnabled) {
      this.skip();
      return;
    }

    const sloId = randomId('adoption-future-schema');
    unsupportedSchemaSloId = sloId;
    unsupportedSchemaGroup = null;

    // Seed a synthetic alert group whose provenance schemaVersion is 999.
    const { namespace, groupName } = {
      namespace: `slo-generated-${datasourceId}`,
      groupName: `slo:alerts:${sloId}_future`,
    };
    unsupportedSchemaGroup = { namespace, groupName };
    seedUnsupportedSchemaOrphan(datasourceId, sloId);

    cy.visit(`/app/${APP_ID}#/slos/adoption`);
    cy.get('[data-test-subj="sloAdoption-page"]', { timeout: 30000 }).should('be.visible');

    // Unsupported-schema never surfaces a Recover button.
    cy.get(`[data-test-subj="sloAdoption-recoverTab-recoverButton-${sloId}"]`).should(
      'not.exist'
    );

    cy.get('[data-test-subj="sloAdoption-recoverTab-unknownsAccordion"]', {
      timeout: 30000,
    })
      .should('be.visible')
      .click();

    // Dedicated "upgrade plugin" cell keyed on sloId. Session B Item 1
    // extended the unknowns envelope with `sourceSloId` + `schemaVersion`,
    // which the UI renders as a danger-colored message.
    cy.get(`[data-test-subj="sloAdoption-recoverTab-unknownsUnsupportedSchema-${sloId}"]`, {
      timeout: 30000,
    })
      .should('be.visible')
      .invoke('text')
      .then((text) => {
        expect(text.toLowerCase()).to.contain('unsupported provenance schemaversion');
      });
  });

  it('does not mention the external dashboards vendor by name anywhere on the adoption page', function () {
    if (!adoptionEnabled) {
      this.skip();
      return;
    }

    cy.visit(`/app/${APP_ID}#/slos/adoption`);
    cy.get('[data-test-subj="sloAdoption-page"]', { timeout: 30000 }).should('be.visible');
    // Plan constraint: no external dashboards vendor named in the DOM.
    cy.contains(/grafana/i).should('not.exist');
  });
});
