/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/// <reference types="cypress" />

/*
 * SLO listing surface — aggregate API + listing chrome.
 *
 * Run locally with:
 *   yarn cypress:run --spec \
 *     .cypress/integration/slo_test/aggregate.spec.js \
 *     --env "sloDatasourceId=ObservabilityStack_Prometheus[,workspaceId=<id>]"
 *
 *   1. _aggregate returns rollups for the SLOs we just created.
 *   2. _aggregate returns 400 when called without `services` or with too
 *      many services.
 *   3. The listing page renders the table, refresh button, search field,
 *      filter accordions for state / service / team / mode, and the
 *      result count line.
 *   4. Clicking Refresh on the listing re-fetches without throwing.
 *
 * Aggregate failure-mode tests are independent of seeded SLOs so they
 * pass even when the create path errors.
 */

const APP_ID = 'observability-apm-slo';
const WORKSPACE_PREFIX = Cypress.env('workspaceId') ? `/w/${Cypress.env('workspaceId')}` : '';
const SLO_BASE = `${WORKSPACE_PREFIX}/api/observability/v1/slos`;
const AGGREGATE_BASE = `${SLO_BASE}/_aggregate`;

const randomId = (prefix) =>
  `${prefix}-${Math.random().toString(36).slice(2, 8)}-${Date.now().toString(36)}`;

function buildSpec(datasourceId, name, service) {
  return {
    datasourceId,
    name,
    description: 'Cypress aggregate spec — autogenerated',
    enabled: true,
    mode: 'active',
    service,
    owner: { teams: ['cypress-team'] },
    sli: {
      type: 'single',
      definition: {
        backend: 'prometheus',
        type: 'availability',
        calcMethod: 'events',
        // Unique metric name per row keeps recording-rule cleanup simple.
        metric: `cypress_aggregate_${name.replace(/[^a-z0-9_]/gi, '_').toLowerCase()}`,
        goodEventsFilter: 'status_code!~"5.."',
      },
      dimensions: [{ name: 'service', value: service }],
    },
    objectives: [{ name: 'primary', target: 0.99 }],
    budgetWarningThresholds: [],
    window: { type: 'rolling', duration: '28d' },
    alerting: {
      strategy: 'mwmbr',
      burnRates: [
        {
          shortWindow: '5m',
          longWindow: '1h',
          burnRateMultiplier: 14.4,
          severity: 'critical',
          createAlarm: true,
          forDuration: '2m',
        },
      ],
    },
    alarms: {
      sliHealth: { enabled: false },
      attainmentBreach: { enabled: false },
      budgetWarning: { enabled: true },
      noData: { enabled: false, forDuration: '10m' },
      resolved: { enabled: false },
    },
    exclusionWindows: [],
    labels: {},
    annotations: {},
  };
}

describe('SLO listing — aggregate API + chrome', () => {
  const datasourceId = Cypress.env('sloDatasourceId') || 'prom_integ_test';
  const svcA = `agg-svc-a-${Math.random().toString(36).slice(2, 6)}`;
  const svcB = `agg-svc-b-${Math.random().toString(36).slice(2, 6)}`;
  const created = [];

  before(() => {
    cy.request({
      method: 'POST',
      url: SLO_BASE,
      headers: { 'osd-xsrf': 'true' },
      body: { spec: buildSpec(datasourceId, randomId('cypress-agg-a'), svcA) },
      failOnStatusCode: false,
    }).then((resp) => {
      if (resp.status === 200 || resp.status === 201) created.push(resp.body.id);
    });
    cy.request({
      method: 'POST',
      url: SLO_BASE,
      headers: { 'osd-xsrf': 'true' },
      body: { spec: buildSpec(datasourceId, randomId('cypress-agg-b'), svcB) },
      failOnStatusCode: false,
    }).then((resp) => {
      if (resp.status === 200 || resp.status === 201) created.push(resp.body.id);
    });
  });

  after(() => {
    created.forEach((id) => {
      cy.request({
        method: 'DELETE',
        url: `${SLO_BASE}/${encodeURIComponent(id)}`,
        headers: { 'osd-xsrf': 'true' },
        failOnStatusCode: false,
      });
    });
  });

  it('_aggregate rolls up health by service for the seeded SLOs', function () {
    if (created.length < 2) {
      this.skip();
      return;
    }
    cy.request({
      method: 'GET',
      url: `${AGGREGATE_BASE}?services=${encodeURIComponent(svcA)},${encodeURIComponent(
        svcB
      )}&datasourceId=${encodeURIComponent(datasourceId)}`,
      headers: { 'osd-xsrf': 'true' },
      failOnStatusCode: false,
    }).then((resp) => {
      expect(resp.status, `aggregate: ${JSON.stringify(resp.body)}`).to.equal(200);
      // Response shape: { bySvc: { [serviceName]: { total, ok, ... } } }.
      // Each requested service appears as a key; the bucket has a `total`
      // count of all SLOs for that service we have access to.
      expect(resp.body).to.have.property('bySvc');
      expect(resp.body.bySvc).to.have.property(svcA);
      expect(resp.body.bySvc).to.have.property(svcB);
      expect(resp.body.bySvc[svcA].total, `svcA total: ${resp.body.bySvc[svcA].total}`)
        .to.be.greaterThan(0);
      expect(resp.body.bySvc[svcB].total, `svcB total: ${resp.body.bySvc[svcB].total}`)
        .to.be.greaterThan(0);
    });
  });

  it('_aggregate returns 400 with an empty services parameter', () => {
    // Empty services value fails the `minLength: 1` schema before reaching
    // the handler, which is also a 400.
    cy.request({
      method: 'GET',
      url: `${AGGREGATE_BASE}?services=&datasourceId=${encodeURIComponent(datasourceId)}`,
      headers: { 'osd-xsrf': 'true' },
      failOnStatusCode: false,
    }).then((resp) => {
      expect(resp.status).to.be.oneOf([400, 422]);
    });
  });

  it('_aggregate returns 400 when too many services are requested', () => {
    // Cap is server-side (MAX_SERVICES_PER_AGGREGATE_CALL = 200 today).
    // Send 250 to trip it without coupling to the exact constant.
    const bigList = Array.from({ length: 250 }, (_, i) => `svc-${i}`).join(',');
    cy.request({
      method: 'GET',
      url: `${AGGREGATE_BASE}?services=${encodeURIComponent(
        bigList
      )}&datasourceId=${encodeURIComponent(datasourceId)}`,
      headers: { 'osd-xsrf': 'true' },
      failOnStatusCode: false,
    }).then((resp) => {
      expect(resp.status).to.be.oneOf([400, 422]);
    });
  });

  it('listing renders the table, search, filter panel, refresh, and result count', () => {
    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos`);
    cy.get('[data-test-subj="slosPage"]', { timeout: 30000 }).should('be.visible');
    cy.get('[data-test-subj="slosTable"]', { timeout: 20000 }).should('be.visible');
    cy.get('[data-test-subj="slosListingFilterSearch"]').should('be.visible');
    cy.get('[data-test-subj="slosListingFilterPanel"]').should('be.visible');
    cy.get('[data-test-subj="slosFilterAccordionService"]').should('be.visible');
    cy.get('[data-test-subj="slosFilterAccordionTeam"]').should('be.visible');
    cy.get('[data-test-subj="slosFilterAccordionState"]').should('be.visible');
    cy.get('[data-test-subj="slosListingResultCount"]').should('be.visible');
    cy.get('[data-test-subj="slosRefresh"]').should('be.visible');
    cy.get('[data-test-subj="slosCreate"]').should('be.visible');
  });

  it('clicking Refresh on the listing re-fetches without errors', () => {
    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos`);
    cy.get('[data-test-subj="slosPage"]', { timeout: 30000 }).should('be.visible');
    cy.get('[data-test-subj="slosTable"]', { timeout: 20000 }).should('be.visible');
    cy.get('[data-test-subj="slosRefresh"]').click();
    // Page stays mounted — no error banner appears.
    cy.get('[data-test-subj="slosPage"]').should('be.visible');
  });
});
