/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/// <reference types="cypress" />

/*
 * SLO API contract: optimistic concurrency, name uniqueness, server-side
 * validation rejections.
 *
 * Run locally with:
 *   yarn cypress:run --spec \
 *     .cypress/integration/slo_test/concurrency.spec.js \
 *     --env "sloDatasourceId=ObservabilityStack_Prometheus[,workspaceId=<id>]"
 *
 * The wizard / UI guards against many bad inputs client-side; this spec
 * pins the SERVER-SIDE invariants that protect the SLO doc from corruption
 * even if a buggy client submits anyway. Each test sends a single request
 * and asserts the failure mode — fast and deterministic.
 *
 *   1. PUT with a stale `version` returns 409 with the current state.
 *   2. POST with a name that collides for the same datasource returns
 *      400 with `spec.name` validation error.
 *   3. POST with an invalid Prometheus metric name returns 400.
 *   4. POST with an invalid `goodEventsFilter` returns 400.
 *   5. POST with a reserved label key (`slo_id`) returns 400.
 *   6. PUT for a non-existent SLO returns 404.
 *   7. DELETE of a non-existent SLO returns 404.
 */

const WORKSPACE_PREFIX = Cypress.env('workspaceId') ? `/w/${Cypress.env('workspaceId')}` : '';
const SLO_BASE = `${WORKSPACE_PREFIX}/api/observability/v1/slos`;

const randomId = (prefix) =>
  `${prefix}-${Math.random().toString(36).slice(2, 8)}-${Date.now().toString(36)}`;

function buildSpec(datasourceId, name, overrides = {}) {
  return {
    datasourceId,
    name,
    description: 'Cypress concurrency spec — autogenerated',
    enabled: true,
    mode: 'active',
    service: 'cypress-svc',
    owner: { teams: ['cypress-team'] },
    sli: {
      type: 'single',
      definition: {
        backend: 'prometheus',
        type: 'availability',
        calcMethod: 'events',
        metric: 'http_requests_total',
        goodEventsFilter: 'status_code!~"5.."',
      },
      dimensions: [{ name: 'service', value: 'cypress-svc' }],
    },
    objectives: [{ name: 'primary', target: 0.99 }],
    budgetWarningThresholds: [],
    window: { type: 'rolling', duration: '28d' },
    alerting: {
      strategy: 'mwmbr',
      burnRates: [
        {
          shortWindow: '5m',
          longWindow: '1h',
          burnRateMultiplier: 14.4,
          severity: 'critical',
          createAlarm: true,
          forDuration: '2m',
        },
      ],
    },
    alarms: {
      sliHealth: { enabled: false },
      attainmentBreach: { enabled: false },
      budgetWarning: { enabled: true },
      noData: { enabled: false, forDuration: '10m' },
      resolved: { enabled: false },
    },
    exclusionWindows: [],
    labels: {},
    annotations: {},
    ...overrides,
  };
}

describe('SLO server-side contract', () => {
  const datasourceId = Cypress.env('sloDatasourceId') || 'prom_integ_test';
  const sloName = randomId('cypress-concur');
  let sloId = null;
  const created = [];

  before(function () {
    cy.request({
      method: 'POST',
      url: SLO_BASE,
      headers: { 'osd-xsrf': 'true' },
      body: { spec: buildSpec(datasourceId, sloName) },
      failOnStatusCode: false,
    }).then((resp) => {
      if (resp.status !== 200 && resp.status !== 201) {
        Cypress.log({
          name: 'concurrency',
          message: `seed failed (${resp.status}); skipping`,
        });
        this.skip();
        return;
      }
      sloId = resp.body.id;
      created.push(sloId);
    });
  });

  after(() => {
    created.forEach((id) => {
      cy.request({
        method: 'DELETE',
        url: `${SLO_BASE}/${encodeURIComponent(id)}`,
        headers: { 'osd-xsrf': 'true' },
        failOnStatusCode: false,
      });
    });
  });

  it('PUT with stale version returns 409', function () {
    if (!sloId) {
      this.skip();
      return;
    }
    cy.request({
      method: 'PUT',
      url: `${SLO_BASE}/${encodeURIComponent(sloId)}`,
      headers: { 'osd-xsrf': 'true' },
      body: { version: 99, spec: { description: 'should-not-land' } },
      failOnStatusCode: false,
    }).then((resp) => {
      expect(resp.status, `PUT stale version: ${JSON.stringify(resp.body)}`).to.equal(409);
      // The route wraps the handler error body under `attributes` (see
      // res.customError() in server/routes/slo/index.ts). The handler-level
      // body carries `attemptedVersion`.
      const attrs = resp.body && (resp.body.attributes || resp.body);
      expect(attrs.attemptedVersion).to.equal(99);
    });
  });

  it('POST with duplicate name returns 400 with spec.name validation error', function () {
    if (!sloId) {
      this.skip();
      return;
    }
    cy.request({
      method: 'POST',
      url: SLO_BASE,
      headers: { 'osd-xsrf': 'true' },
      body: { spec: buildSpec(datasourceId, sloName) },
      failOnStatusCode: false,
    }).then((resp) => {
      expect(resp.status, `dup name: ${JSON.stringify(resp.body)}`).to.equal(400);
      const errors =
        (resp.body && resp.body.attributes && resp.body.attributes.errors) ||
        (resp.body && resp.body.errors) ||
        {};
      expect(JSON.stringify(errors)).to.match(/spec\.name/);
    });
  });

  it('POST with invalid metric name returns 400', () => {
    cy.request({
      method: 'POST',
      url: SLO_BASE,
      headers: { 'osd-xsrf': 'true' },
      body: {
        spec: buildSpec(datasourceId, randomId('cypress-bad-metric'), {
          sli: {
            type: 'single',
            definition: {
              backend: 'prometheus',
              type: 'availability',
              calcMethod: 'events',
              // Leading digit + hyphen — not a valid Prometheus metric name.
              metric: '1bad-metric',
              goodEventsFilter: 'status_code!~"5.."',
            },
            dimensions: [{ name: 'service', value: 'cypress-svc' }],
          },
        }),
      },
      failOnStatusCode: false,
    }).then((resp) => {
      expect(resp.status, `bad metric: ${JSON.stringify(resp.body)}`).to.be.oneOf([400, 422]);
    });
  });

  it('POST with malformed goodEventsFilter returns 400', () => {
    cy.request({
      method: 'POST',
      url: SLO_BASE,
      headers: { 'osd-xsrf': 'true' },
      body: {
        spec: buildSpec(datasourceId, randomId('cypress-bad-filter'), {
          sli: {
            type: 'single',
            definition: {
              backend: 'prometheus',
              type: 'availability',
              calcMethod: 'events',
              metric: 'http_requests_total',
              // Multiple matchers separated by comma — explicitly disallowed
              // (would let a caller smuggle an extra label matcher through).
              goodEventsFilter: 'status_code!~"5..",pwn="y"',
            },
            dimensions: [{ name: 'service', value: 'cypress-svc' }],
          },
        }),
      },
      failOnStatusCode: false,
    }).then((resp) => {
      expect(resp.status, `bad filter: ${JSON.stringify(resp.body)}`).to.be.oneOf([400, 422]);
    });
  });

  it('POST with reserved label key returns 400', () => {
    cy.request({
      method: 'POST',
      url: SLO_BASE,
      headers: { 'osd-xsrf': 'true' },
      body: {
        spec: buildSpec(datasourceId, randomId('cypress-reserved-label'), {
          // Reserved keys would clobber the system-emitted labels
          // (slo_id, slo_name, ...) — see RESERVED_LABEL_KEYS in
          // common/slo/slo_validators.ts.
          labels: { slo_id: 'attacker-controlled' },
        }),
      },
      failOnStatusCode: false,
    }).then((resp) => {
      expect(resp.status, `reserved label: ${JSON.stringify(resp.body)}`).to.be.oneOf([400, 422]);
    });
  });

  it('PUT for a non-existent SLO returns 404', () => {
    cy.request({
      method: 'PUT',
      url: `${SLO_BASE}/${encodeURIComponent('00000000-0000-0000-0000-000000000000')}`,
      headers: { 'osd-xsrf': 'true' },
      body: { version: 1, spec: { description: 'no-such-slo' } },
      failOnStatusCode: false,
    }).then((resp) => {
      expect(resp.status).to.equal(404);
    });
  });

  it('DELETE for a non-existent SLO returns 404', () => {
    cy.request({
      method: 'DELETE',
      url: `${SLO_BASE}/${encodeURIComponent('00000000-0000-0000-0000-000000000000')}`,
      headers: { 'osd-xsrf': 'true' },
      failOnStatusCode: false,
    }).then((resp) => {
      expect(resp.status).to.equal(404);
    });
  });
});
