/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/// <reference types="cypress" />

/*
 * SLO rule-dedup end-to-end.
 *
 * Run locally with:
 *   yarn cypress:run-without-security --spec \
 *     .cypress/integration/slo_test/dedup.spec.js
 *
 * Requires the observability-stack dev cluster (Cortex-backed `prometheus`
 * container + a DirectQuery datasource named by `sloDatasourceId`). The
 * spec exercises the dedup contract from the user's perspective:
 *
 *   1. Create two SLOs that share the same SLI shape. Both land.
 *   2. Open the first SLO's detail page — the "Shared with 1 other SLO"
 *      pill renders and the recording-rule accordion lists the
 *      fingerprint-keyed rule names.
 *   3. Edit the second SLO's ruler-neutral fields (description). The
 *      detail page for the first SLO keeps its shared-with pill — peer
 *      SLOs are not side-affected by updates that don't touch the SLI.
 *   4. Delete the second SLO. The first keeps its recording rules
 *      (refcount=1, no synchronous recording-group deletion).
 *   5. Delete the first SLO. The refcount drops to zero and the
 *      recording group is queued for the grace sweep.
 *
 * Cleanup runs the live DELETE in `after` so no SLOs leak between runs.
 */

const APP_ID = 'observability-apm-slo';
const WORKSPACE_PREFIX = Cypress.env('workspaceId') ? `/w/${Cypress.env('workspaceId')}` : '';
const SLO_BASE = `${WORKSPACE_PREFIX}/api/observability/v1/slos`;

const randomId = (prefix) =>
  `${prefix}-${Math.random().toString(36).slice(2, 8)}-${Date.now().toString(36)}`;

function buildSharedSloSpec(datasourceId, name) {
  return {
    datasourceId,
    name,
    description: 'Cypress dedup spec — autogenerated',
    enabled: true,
    mode: 'active',
    service: 'cypress-svc',
    owner: { teams: ['cypress-team'] },
    sli: {
      type: 'single',
      definition: {
        backend: 'prometheus',
        type: 'availability',
        calcMethod: 'events',
        // Same metric + filter across SLOs A and B — this drives the shared
        // fingerprint.
        metric: 'http_requests_total',
        goodEventsFilter: 'status_code!~"5.."',
      },
      dimensions: [{ name: 'service', value: 'cypress-svc' }],
    },
    objectives: [{ name: 'primary', target: 0.99 }],
    budgetWarningThresholds: [],
    window: { type: 'rolling', duration: '28d' },
    alerting: {
      strategy: 'mwmbr',
      burnRates: [
        {
          shortWindow: '5m',
          longWindow: '1h',
          burnRateMultiplier: 14.4,
          severity: 'critical',
          createAlarm: true,
          forDuration: '2m',
        },
      ],
    },
    alarms: {
      sliHealth: { enabled: false },
      attainmentBreach: { enabled: false },
      budgetWarning: { enabled: true },
      noData: { enabled: false, forDuration: '10m' },
      resolved: { enabled: false },
    },
    exclusionWindows: [],
    labels: {},
    annotations: {},
  };
}

describe('SLO rule dedup — detail UX', () => {
  const datasourceId = Cypress.env('sloDatasourceId') || 'prom_integ_test';
  const nameA = randomId('cypress-dedup-a');
  const nameB = randomId('cypress-dedup-b');
  let sloIdA = null;
  let sloIdB = null;

  before(() => {
    cy.request({
      method: 'POST',
      url: SLO_BASE,
      headers: { 'osd-xsrf': 'true' },
      body: { spec: buildSharedSloSpec(datasourceId, nameA) },
      failOnStatusCode: false,
    }).then((resp) => {
      if (resp.status === 200 || resp.status === 201) {
        sloIdA = resp.body.id;
      }
    });
    cy.request({
      method: 'POST',
      url: SLO_BASE,
      headers: { 'osd-xsrf': 'true' },
      body: { spec: buildSharedSloSpec(datasourceId, nameB) },
      failOnStatusCode: false,
    }).then((resp) => {
      if (resp.status === 200 || resp.status === 201) {
        sloIdB = resp.body.id;
      }
    });
  });

  after(() => {
    if (sloIdA) {
      cy.request({
        method: 'DELETE',
        url: `${SLO_BASE}/${encodeURIComponent(sloIdA)}`,
        headers: { 'osd-xsrf': 'true' },
        failOnStatusCode: false,
      });
    }
    if (sloIdB) {
      cy.request({
        method: 'DELETE',
        url: `${SLO_BASE}/${encodeURIComponent(sloIdB)}`,
        headers: { 'osd-xsrf': 'true' },
        failOnStatusCode: false,
      });
    }
  });

  it('A and B share recording rules — detail page shows the pill + fingerprint-keyed names', function () {
    if (!sloIdA || !sloIdB) {
      this.skip();
      return;
    }

    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos/${encodeURIComponent(sloIdA)}`);
    cy.get('[data-test-subj="sloDetailPage"]', { timeout: 30000 }).should('be.visible');

    // Recording-rule accordion is nested inside the (collapsed-by-default)
    // "Advanced details" accordion — expand the parent first.
    cy.get('[data-test-subj="slosDetailAdvancedAccordion"]').click();
    cy.get('[data-test-subj="slosDetailRecordingRulesAccordion"]').click();
    cy.get('[data-test-subj^="slosDetailRecordingRule-"]')
      .should('have.length.greaterThan', 0)
      .each(($el) => {
        // Dedup names match `slo:sli_error:ratio_rate_<w>:sli_<fp>`.
        cy.wrap($el).invoke('text').should('match', /slo:sli_error:ratio_rate_.+:sli_[0-9a-f]{16}/);
      });

    // Shared-with pill: refcount is 2 (A + B), so "N others" = 1.
    cy.get('[data-test-subj="slosDetailSharedWithPill"]')
      .should('be.visible')
      .and('contain.text', 'Shared with 1 other SLO');
  });

  it('editing B (non-SLI field) does not affect A', function () {
    if (!sloIdA || !sloIdB) {
      this.skip();
      return;
    }

    cy.request({
      method: 'PUT',
      url: `${SLO_BASE}/${encodeURIComponent(sloIdB)}`,
      headers: { 'osd-xsrf': 'true' },
      body: {
        spec: { description: 'Cypress dedup spec — updated description' },
        version: 1,
      },
      failOnStatusCode: false,
    });

    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos/${encodeURIComponent(sloIdA)}`);
    cy.get('[data-test-subj="sloDetailPage"]', { timeout: 30000 }).should('be.visible');
    cy.get('[data-test-subj="slosDetailSharedWithPill"]').should('contain.text', 'Shared with 1 other SLO');
  });

  it('deleting B: the refcount on A drops to 1, pill disappears', function () {
    if (!sloIdA || !sloIdB) {
      this.skip();
      return;
    }

    cy.request({
      method: 'DELETE',
      url: `${SLO_BASE}/${encodeURIComponent(sloIdB)}`,
      headers: { 'osd-xsrf': 'true' },
      failOnStatusCode: false,
    }).then((resp) => {
      expect(resp.status, `DELETE B response: ${JSON.stringify(resp.body)}`).to.be.oneOf([
        200,
        201,
        204,
      ]);
    });
    // Clear so the after-hook doesn't double-delete.
    sloIdB = null;

    // Refresh A's detail page, then force a hard reload to bypass any
    // browser-side caches before checking the pill state.
    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos/${encodeURIComponent(sloIdA)}`);
    cy.reload(true);
    cy.get('[data-test-subj="sloDetailPage"]', { timeout: 30000 }).should('be.visible');
    // Pill is hidden once we're the only SLO referencing the fingerprint.
    cy.get('[data-test-subj="slosDetailSharedWithPill"]', { timeout: 30000 }).should('not.exist');
    // Recording rule names still render — the group lives on.
    cy.get('[data-test-subj="slosDetailAdvancedAccordion"]').click();
    cy.get('[data-test-subj="slosDetailRecordingRulesAccordion"]').click();
    cy.get('[data-test-subj^="slosDetailRecordingRule-"]').should('have.length.greaterThan', 0);
  });
});
