/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/// <reference types="cypress" />

/*
 * SLO dedup warning copy.
 *
 * Run locally with:
 *   yarn cypress:run-without-security --spec \
 *     .cypress/integration/slo_test/dedup_warning_copy.spec.js
 *
 * Pins the user-visible copy on the dedup-aware delete modal:
 *
 *   1. The modal mentions the per-SLO alert group by name, the 24h grace
 *      period, and the "shared recording rules" language — so operators
 *      understand what is removed immediately vs. what is reference-counted.
 *   2. The modal's DOM contains no "Grafana" string — dashboards must be
 *      spoken of generically.
 *
 * Creates one SLO live and asserts the modal DOM; does not actually confirm
 * the delete until cleanup.
 */

const APP_ID = 'observability-apm-slo';
const WORKSPACE_PREFIX = Cypress.env('workspaceId') ? `/w/${Cypress.env('workspaceId')}` : '';
const SLO_BASE = `${WORKSPACE_PREFIX}/api/observability/v1/slos`;

const randomId = (prefix) =>
  `${prefix}-${Math.random().toString(36).slice(2, 8)}-${Date.now().toString(36)}`;

function buildMinimalSloSpec(datasourceId, name) {
  return {
    datasourceId,
    name,
    description: 'Cypress dedup warning-copy spec — autogenerated',
    enabled: true,
    mode: 'active',
    service: 'cypress-svc',
    owner: { teams: ['cypress-team'] },
    sli: {
      type: 'single',
      definition: {
        backend: 'prometheus',
        type: 'availability',
        calcMethod: 'events',
        metric: 'http_requests_total',
        goodEventsFilter: 'status_code!~"5.."',
      },
      dimensions: [{ name: 'service', value: 'cypress-svc' }],
    },
    objectives: [{ name: 'primary', target: 0.99 }],
    budgetWarningThresholds: [],
    window: { type: 'rolling', duration: '28d' },
    alerting: {
      strategy: 'mwmbr',
      burnRates: [
        {
          shortWindow: '5m',
          longWindow: '1h',
          burnRateMultiplier: 14.4,
          severity: 'critical',
          createAlarm: true,
          forDuration: '2m',
        },
      ],
    },
    alarms: {
      sliHealth: { enabled: false },
      attainmentBreach: { enabled: false },
      budgetWarning: { enabled: true },
      noData: { enabled: false, forDuration: '10m' },
      resolved: { enabled: false },
    },
    exclusionWindows: [],
    labels: {},
    annotations: {},
  };
}

describe('SLO dedup warning copy', () => {
  const datasourceId = Cypress.env('sloDatasourceId') || 'prom_integ_test';
  const sloName = randomId('cypress-dedup-copy');
  let sloId = null;

  before(() => {
    cy.request({
      method: 'POST',
      url: SLO_BASE,
      headers: { 'osd-xsrf': 'true' },
      body: { spec: buildMinimalSloSpec(datasourceId, sloName) },
      failOnStatusCode: false,
    }).then((resp) => {
      if (resp.status === 200 || resp.status === 201) {
        sloId = resp.body.id;
      }
    });
  });

  after(() => {
    if (!sloId) return;
    cy.request({
      method: 'DELETE',
      url: `${SLO_BASE}/${encodeURIComponent(sloId)}`,
      headers: { 'osd-xsrf': 'true' },
      failOnStatusCode: false,
    });
  });

  it('delete-modal surfaces dedup-aware copy and contains no "Grafana" references', function () {
    if (!sloId) {
      this.skip();
      return;
    }

    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos/${encodeURIComponent(sloId)}`);
    cy.get('[data-test-subj="sloDetailPage"]', { timeout: 30000 }).should('be.visible');

    cy.get('[data-test-subj="slosDetailDelete"]').click();
    cy.get('[data-test-subj="slosDetailDeleteModal"]', { timeout: 10000 }).should('be.visible');

    // Core dedup phrases — case-insensitive match against the modal body.
    cy.get('[data-test-subj="slosDetailDeleteModal"]')
      .invoke('text')
      .then((text) => {
        const lower = text.toLowerCase();
        expect(lower).to.match(/alert group/);
        expect(lower).to.match(/shared recording rules/);
        expect(lower).to.match(/24h grace|24 hour/);
        // No "Grafana" anywhere — plan constraint.
        expect(lower).to.not.match(/grafana/);
      });

    // Close without deleting.
    cy.get('[data-test-subj="confirmModalCancelButton"]').click();
  });

  it('recording-rules accordion explainer speaks of external dashboards, not Grafana', function () {
    if (!sloId) {
      this.skip();
      return;
    }

    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos/${encodeURIComponent(sloId)}`);
    cy.get('[data-test-subj="sloDetailPage"]', { timeout: 30000 }).should('be.visible');
    // Recording-rule accordion is nested inside Advanced details (collapsed
    // by default).
    cy.get('[data-test-subj="slosDetailAdvancedAccordion"]').click();
    cy.get('[data-test-subj="slosDetailRecordingRulesAccordion"]').click();
    cy.get('[data-test-subj="slosDetailRecordingRulesAccordion"]')
      .invoke('text')
      .then((text) => {
        expect(text.toLowerCase()).to.not.match(/grafana/);
      });
  });
});
