/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/// <reference types="cypress" />

/*
 * SLO detail page — every panel must render.
 *
 * Run locally with:
 *   yarn cypress:run --spec \
 *     .cypress/integration/slo_test/detail_panels.spec.js \
 *     --env "sloDatasourceId=ObservabilityStack_Prometheus[,workspaceId=<id>]"
 *
 * The detail page composes ~10 panels. A regression that breaks any single
 * panel's render is hard to catch from snapshot tests alone (e.g. an
 * objective-row formatter that throws on empty data, a chart that errors
 * when the metric series are missing). This spec drives every visible
 * panel for one healthy and one shadow-mode SLO and asserts the panel
 * containers exist + key sub-elements render.
 *
 * What we cover:
 *   1. Header with health dot, title, attainment hero, target/delta line.
 *   2. Summary & SLI accordion with both lists.
 *   3. Burn-rate chart panel.
 *   4. Burn-rate tiers panel (per-window).
 *   5. Budget-remaining chart panel.
 *   6. Budget panel with bar.
 *   7. Alerts panel.
 *   8. Objectives table.
 *   9. Advanced details with recording rules accordion.
 *   10. Shadow-mode SLO renders the shadow badge, doesn't render alerts.
 */

const APP_ID = 'observability-apm-slo';
const WORKSPACE_PREFIX = Cypress.env('workspaceId') ? `/w/${Cypress.env('workspaceId')}` : '';
const SLO_BASE = `${WORKSPACE_PREFIX}/api/observability/v1/slos`;

const randomId = (prefix) =>
  `${prefix}-${Math.random().toString(36).slice(2, 8)}-${Date.now().toString(36)}`;

function buildSpec(datasourceId, name, { mode = 'active', enabled = true } = {}) {
  return {
    datasourceId,
    name,
    description: 'Cypress detail_panels spec — autogenerated',
    enabled,
    mode,
    service: 'cypress-svc',
    owner: { teams: ['cypress-team'] },
    sli: {
      type: 'single',
      definition: {
        backend: 'prometheus',
        type: 'availability',
        calcMethod: 'events',
        metric: 'http_requests_total',
        goodEventsFilter: 'status_code!~"5.."',
      },
      dimensions: [{ name: 'service', value: 'cypress-svc' }],
    },
    objectives: [{ name: 'primary', target: 0.99 }],
    budgetWarningThresholds: [{ threshold: 0.5, severity: 'warning' }],
    window: { type: 'rolling', duration: '28d' },
    alerting: {
      strategy: 'mwmbr',
      burnRates: [
        {
          shortWindow: '5m',
          longWindow: '1h',
          burnRateMultiplier: 14.4,
          severity: 'critical',
          createAlarm: true,
          forDuration: '2m',
        },
      ],
    },
    alarms: {
      sliHealth: { enabled: false },
      attainmentBreach: { enabled: false },
      budgetWarning: { enabled: true },
      noData: { enabled: false, forDuration: '10m' },
      resolved: { enabled: false },
    },
    exclusionWindows: [],
    labels: {},
    annotations: {},
  };
}

describe('SLO detail page — panels render', () => {
  const datasourceId = Cypress.env('sloDatasourceId') || 'prom_integ_test';
  const nameActive = randomId('cypress-detail-active');
  const nameShadow = randomId('cypress-detail-shadow');
  let activeId = null;
  let shadowId = null;

  before(function () {
    cy.request({
      method: 'POST',
      url: SLO_BASE,
      headers: { 'osd-xsrf': 'true' },
      body: { spec: buildSpec(datasourceId, nameActive, { mode: 'active' }) },
      failOnStatusCode: false,
    }).then((resp) => {
      if (resp.status === 200 || resp.status === 201) activeId = resp.body.id;
    });
    cy.request({
      method: 'POST',
      url: SLO_BASE,
      headers: { 'osd-xsrf': 'true' },
      body: { spec: buildSpec(datasourceId, nameShadow, { mode: 'shadow' }) },
      failOnStatusCode: false,
    }).then((resp) => {
      if (resp.status === 200 || resp.status === 201) shadowId = resp.body.id;
    });
  });

  after(() => {
    [activeId, shadowId].forEach((id) => {
      if (!id) return;
      cy.request({
        method: 'DELETE',
        url: `${SLO_BASE}/${encodeURIComponent(id)}`,
        headers: { 'osd-xsrf': 'true' },
        failOnStatusCode: false,
      });
    });
  });

  it('active SLO: header, attainment hero, summary accordion, objectives table all render', function () {
    if (!activeId) {
      this.skip();
      return;
    }
    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos/${encodeURIComponent(activeId)}`);
    cy.get('[data-test-subj="sloDetailPage"]', { timeout: 30000 }).should('be.visible');

    cy.get('[data-test-subj="slosDetailHeader"]').should('be.visible');
    cy.get('[data-test-subj="slosDetailHealthDot"]').should('exist');
    cy.get('[data-test-subj="slosDetailTitle"]').should('contain.text', nameActive);
    cy.get('[data-test-subj="slosDetailAttainmentHero"]').should('be.visible');
    cy.get('[data-test-subj="slosDetailAttainmentTargetDelta"]').should('contain.text', 'Target');
    cy.get('[data-test-subj="slosDetailMetaStrip"]').should('be.visible');

    // Summary & SLI accordion populates both descriptions when expanded.
    cy.get('[data-test-subj="slosDetailSummaryAccordion"]').click();
    cy.get('[data-test-subj="slosDetailSummaryList"]').should('be.visible');
    cy.get('[data-test-subj="slosDetailSliList"]').should('be.visible');

    // Objectives table renders one row for the single objective.
    cy.get('[data-test-subj="slosDetailObjectivesTable"]').should('be.visible')
      .and('contain.text', 'primary');
  });

  it('active SLO: visualizations + alerts panel render', function () {
    if (!activeId) {
      this.skip();
      return;
    }
    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos/${encodeURIComponent(activeId)}`);
    cy.get('[data-test-subj="sloDetailPage"]', { timeout: 30000 }).should('be.visible');

    // The visualizations block is gated on an APM-configured Prometheus
    // datasource (set via the APM Settings modal, persisted as a saved
    // object). When configured: the burn-rate, budget-remaining, and
    // burn-rate-tier panels render. When not configured (CI default):
    // SloVisualizations short-circuits to a single fallback callout.
    // Either path is a valid mount, so we accept either marker.
    cy.get(
      '[data-test-subj="slosBurnRateChart"], [data-test-subj="slosVisualizationsNoDatasource"]',
      { timeout: 20000 }
    ).should('be.visible');
    cy.get('body').then(($body) => {
      if ($body.find('[data-test-subj="slosBurnRateChart"]').length > 0) {
        cy.get('[data-test-subj="slosBudgetRemainingChart"]').should('be.visible');
        cy.get('[data-test-subj="slosBurnratePanel"]').should('be.visible');
      }
    });
    // Alerts panel is independent of the APM datasource config and always
    // renders for non-composite SLOs.
    cy.get('[data-test-subj="slosDetailAlertsPanel"]').should('be.visible');
  });

  it('active SLO: advanced accordion expands to show recording rules + alert group', function () {
    if (!activeId) {
      this.skip();
      return;
    }
    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos/${encodeURIComponent(activeId)}`);
    cy.get('[data-test-subj="sloDetailPage"]', { timeout: 30000 }).should('be.visible');

    // Advanced details is collapsed by default.
    cy.get('[data-test-subj="slosDetailAdvancedAccordion"]').click();
    cy.get('[data-test-subj="slosDetailAdvancedOps"]').should('exist');
    cy.get('[data-test-subj="slosDetailRecordingRulesAccordion"]').click();
    cy.get('[data-test-subj^="slosDetailRecordingRule-"]')
      .should('have.length.greaterThan', 0);
  });

  it('active SLO: View alert rules + Toggle + Delete buttons exist in the header', function () {
    if (!activeId) {
      this.skip();
      return;
    }
    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos/${encodeURIComponent(activeId)}`);
    cy.get('[data-test-subj="sloDetailPage"]', { timeout: 30000 }).should('be.visible');
    cy.get('[data-test-subj="slosDetailViewRules"]').should('exist');
    cy.get('[data-test-subj="slosDetailToggle"]').should('be.visible')
      .and('contain.text', 'Disable');
    cy.get('[data-test-subj="slosDetailDelete"]').should('be.visible');
    cy.get('[data-test-subj="slosBack"]').should('exist');
  });

  it('shadow-mode SLO: shadow badge renders, page still mounts', function () {
    if (!shadowId) {
      this.skip();
      return;
    }
    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos/${encodeURIComponent(shadowId)}`);
    cy.get('[data-test-subj="sloDetailPage"]', { timeout: 30000 }).should('be.visible');
    cy.get('[data-test-subj="slosDetailModeBadge"]', { timeout: 20000 }).should(
      'contain.text',
      'shadow'
    );
    // The header + objectives table still render even in shadow mode.
    cy.get('[data-test-subj="slosDetailHeader"]').should('be.visible');
    cy.get('[data-test-subj="slosDetailObjectivesTable"]').should('be.visible');
  });
});
