/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/// <reference types="cypress" />

/*
 * SLO enable/disable round-trip.
 *
 * Run locally with:
 *   yarn cypress:run --spec \
 *     .cypress/integration/slo_test/enable_disable.spec.js \
 *     --env "sloDatasourceId=ObservabilityStack_Prometheus[,workspaceId=<id>]"
 *
 * Disable surfaces a "Disabled" badge on the detail page header. The
 * listing's enabled facet must reflect the change, and the toggle button
 * label flips between "Disable" and "Enable". This guards the UI ↔ ruler
 * dual-write contract for the disable path: when an SLO is disabled, the
 * recording group lives on but alert evaluation halts.
 */

const APP_ID = 'observability-apm-slo';
const WORKSPACE_PREFIX = Cypress.env('workspaceId') ? `/w/${Cypress.env('workspaceId')}` : '';
const SLO_BASE = `${WORKSPACE_PREFIX}/api/observability/v1/slos`;

const randomId = (prefix) =>
  `${prefix}-${Math.random().toString(36).slice(2, 8)}-${Date.now().toString(36)}`;

function buildSpec(datasourceId, name) {
  return {
    datasourceId,
    name,
    description: 'Cypress enable_disable spec — autogenerated',
    enabled: true,
    mode: 'active',
    service: 'cypress-svc',
    owner: { teams: ['cypress-team'] },
    sli: {
      type: 'single',
      definition: {
        backend: 'prometheus',
        type: 'availability',
        calcMethod: 'events',
        metric: 'http_requests_total',
        goodEventsFilter: 'status_code!~"5.."',
      },
      dimensions: [{ name: 'service', value: 'cypress-svc' }],
    },
    objectives: [{ name: 'primary', target: 0.99 }],
    budgetWarningThresholds: [],
    window: { type: 'rolling', duration: '28d' },
    alerting: {
      strategy: 'mwmbr',
      burnRates: [
        {
          shortWindow: '5m',
          longWindow: '1h',
          burnRateMultiplier: 14.4,
          severity: 'critical',
          createAlarm: true,
          forDuration: '2m',
        },
      ],
    },
    alarms: {
      sliHealth: { enabled: false },
      attainmentBreach: { enabled: false },
      budgetWarning: { enabled: true },
      noData: { enabled: false, forDuration: '10m' },
      resolved: { enabled: false },
    },
    exclusionWindows: [],
    labels: {},
    annotations: {},
  };
}

describe('SLO enable/disable round-trip', () => {
  const datasourceId = Cypress.env('sloDatasourceId') || 'prom_integ_test';
  const sloName = randomId('cypress-toggle');
  let sloId = null;

  before(function () {
    cy.request({
      method: 'POST',
      url: SLO_BASE,
      headers: { 'osd-xsrf': 'true' },
      body: { spec: buildSpec(datasourceId, sloName) },
      failOnStatusCode: false,
    }).then((resp) => {
      if (resp.status === 200 || resp.status === 201) {
        sloId = resp.body.id;
      } else {
        Cypress.log({ name: 'enable_disable', message: `create failed (${resp.status})` });
        this.skip();
      }
    });
  });

  after(() => {
    if (!sloId) return;
    cy.request({
      method: 'DELETE',
      url: `${SLO_BASE}/${encodeURIComponent(sloId)}`,
      headers: { 'osd-xsrf': 'true' },
      failOnStatusCode: false,
    });
  });

  it('toggle flips between Disable and Enable, surfaces the disabled badge, and persists', function () {
    if (!sloId) {
      this.skip();
      return;
    }
    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos/${encodeURIComponent(sloId)}`);
    cy.get('[data-test-subj="sloDetailPage"]', { timeout: 30000 }).should('be.visible');

    // Initial state: enabled, button reads "Disable", no disabled badge.
    cy.get('[data-test-subj="slosDetailToggle"]').should('contain.text', 'Disable');
    cy.get('[data-test-subj="slosDetailDisabledBadge"]').should('not.exist');

    // Click Disable.
    cy.get('[data-test-subj="slosDetailToggle"]').click();

    // Badge appears; toggle now reads "Enable".
    cy.get('[data-test-subj="slosDetailDisabledBadge"]', { timeout: 20000 }).should(
      'be.visible'
    );
    cy.get('[data-test-subj="slosDetailToggle"]').should('contain.text', 'Enable');

    // Persists across reload — bypass HTTP cache so we see the new doc.
    cy.reload(true);
    cy.get('[data-test-subj="sloDetailPage"]', { timeout: 30000 }).should('be.visible');
    cy.get('[data-test-subj="slosDetailDisabledBadge"]').should('be.visible');
    cy.get('[data-test-subj="slosDetailToggle"]').should('contain.text', 'Enable');

    // Click Enable; the badge disappears and label flips back.
    cy.get('[data-test-subj="slosDetailToggle"]').click();
    cy.get('[data-test-subj="slosDetailDisabledBadge"]', { timeout: 20000 }).should('not.exist');
    cy.get('[data-test-subj="slosDetailToggle"]').should('contain.text', 'Disable');
  });

  it('disable via API: the listing row state reflects the change after refresh', function () {
    if (!sloId) {
      this.skip();
      return;
    }
    // Disable through the API.
    cy.request({
      method: 'POST',
      url: `${SLO_BASE}/${encodeURIComponent(sloId)}/disable`,
      headers: { 'osd-xsrf': 'true' },
      failOnStatusCode: false,
    }).then((resp) => {
      expect(resp.status, `disable: ${resp.status}`).to.equal(200);
    });

    // Listing filtered by enabled=false should include this SLO.
    cy.request({
      method: 'GET',
      url: `${SLO_BASE}?pageSize=500&enabled=false`,
      headers: { 'osd-xsrf': 'true' },
      failOnStatusCode: false,
    }).then((resp) => {
      expect(resp.status).to.equal(200);
      const ids = (resp.body.results || []).map((it) => it.id);
      expect(ids).to.include(sloId);
    });

    // Re-enable so cleanup matches the freshly-created state.
    cy.request({
      method: 'POST',
      url: `${SLO_BASE}/${encodeURIComponent(sloId)}/enable`,
      headers: { 'osd-xsrf': 'true' },
      failOnStatusCode: false,
    });
  });
});
