/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/// <reference types="cypress" />

/*
 * SLO listing — filter & search behaviour.
 *
 * Run locally with:
 *   yarn cypress:run --spec \
 *     .cypress/integration/slo_test/listing_filters.spec.js \
 *     --env "sloDatasourceId=ObservabilityStack_Prometheus[,workspaceId=<id>]"
 *
 * Seeds three SLOs that vary in service / team / name, then drives the
 * listing's URL-based filter + search controls to confirm rows are
 * narrowed correctly. The hash search params (`?service=`, `?team=`,
 * `?search=`) are part of the listing's deep-link contract — we exercise
 * them directly so the test stays fast and is independent of accordion
 * UI mechanics that change shape over time.
 *
 *   1. ?service=<X> — only rows whose service is X are visible.
 *   2. ?team=<Y> — only rows whose owner team is Y are visible.
 *   3. ?search=<substr> — name-substring matches show; non-matches hide.
 *   4. ?search=<no-such> — empty-filtered prompt renders, with a clear
 *      button that returns the listing to the unfiltered state.
 */

const APP_ID = 'observability-apm-slo';
const WORKSPACE_PREFIX = Cypress.env('workspaceId') ? `/w/${Cypress.env('workspaceId')}` : '';
const SLO_BASE = `${WORKSPACE_PREFIX}/api/observability/v1/slos`;

const randomId = (prefix) =>
  `${prefix}-${Math.random().toString(36).slice(2, 8)}-${Date.now().toString(36)}`;

const SVC_FOO = `cypress-svc-foo-${Math.random().toString(36).slice(2, 6)}`;
const SVC_BAR = `cypress-svc-bar-${Math.random().toString(36).slice(2, 6)}`;
const TEAM_RED = `cypress-team-red-${Math.random().toString(36).slice(2, 6)}`;
const TEAM_BLUE = `cypress-team-blue-${Math.random().toString(36).slice(2, 6)}`;

function buildSpec({ datasourceId, name, service, team }) {
  return {
    datasourceId,
    name,
    description: 'Cypress listing_filters spec — autogenerated',
    enabled: true,
    mode: 'active',
    service,
    owner: { teams: [team] },
    sli: {
      type: 'single',
      definition: {
        backend: 'prometheus',
        type: 'availability',
        calcMethod: 'events',
        // Each SLO uses a unique metric so dedup doesn't merge groups —
        // not strictly necessary for this spec, but keeps cleanup simple.
        metric: `cypress_listing_${name.replace(/[^a-z0-9_]/gi, '_').toLowerCase()}`,
        goodEventsFilter: 'status_code!~"5.."',
      },
      dimensions: [{ name: 'service', value: service }],
    },
    objectives: [{ name: 'primary', target: 0.99 }],
    budgetWarningThresholds: [],
    window: { type: 'rolling', duration: '28d' },
    alerting: {
      strategy: 'mwmbr',
      burnRates: [
        {
          shortWindow: '5m',
          longWindow: '1h',
          burnRateMultiplier: 14.4,
          severity: 'critical',
          createAlarm: true,
          forDuration: '2m',
        },
      ],
    },
    alarms: {
      sliHealth: { enabled: false },
      attainmentBreach: { enabled: false },
      budgetWarning: { enabled: true },
      noData: { enabled: false, forDuration: '10m' },
      resolved: { enabled: false },
    },
    exclusionWindows: [],
    labels: {},
    annotations: {},
  };
}

describe('SLO listing — filter & search', () => {
  const datasourceId = Cypress.env('sloDatasourceId') || 'prom_integ_test';
  // Three SLOs across two services and two teams. Names embed unique
  // hyphen-separated tokens; OSD saved-object search tokenizes the `name`
  // field on hyphens and runs case-insensitive prefix matching, so each
  // token narrows to exactly one row.
  const tokA = `unicorna${Math.random().toString(36).slice(2, 6)}`;
  const tokB = `unicornb${Math.random().toString(36).slice(2, 6)}`;
  const nameA = `cypress-list-${tokA}-${Date.now().toString(36)}`;
  const nameB = `cypress-list-${tokB}-${Date.now().toString(36)}`;
  const nameC = randomId('cypress-list-c');
  const created = [];

  before(function () {
    const seed = (spec) =>
      cy
        .request({
          method: 'POST',
          url: SLO_BASE,
          headers: { 'osd-xsrf': 'true' },
          body: { spec },
          failOnStatusCode: false,
        })
        .then((resp) => {
          if (resp.status === 200 || resp.status === 201) {
            created.push(resp.body.id);
            return resp.body.id;
          }
          return null;
        });

    seed(buildSpec({ datasourceId, name: nameA, service: SVC_FOO, team: TEAM_RED }));
    seed(buildSpec({ datasourceId, name: nameB, service: SVC_FOO, team: TEAM_BLUE }));
    seed(buildSpec({ datasourceId, name: nameC, service: SVC_BAR, team: TEAM_RED })).then(() => {
      // If any of the 3 creates failed (e.g. Cortex unavailable in this env),
      // skip the spec rather than chase a partial setup.
      if (created.length < 3) {
        Cypress.log({
          name: 'listing_filters',
          message: `Only ${created.length}/3 SLOs created; skipping spec`,
        });
        this.skip();
      }
    });
  });

  after(() => {
    created.forEach((id) => {
      cy.request({
        method: 'DELETE',
        url: `${SLO_BASE}/${encodeURIComponent(id)}`,
        headers: { 'osd-xsrf': 'true' },
        failOnStatusCode: false,
      });
    });
  });

  it(`?service= narrows to rows matching that service`, function () {
    if (created.length < 3) {
      this.skip();
      return;
    }
    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos?service=${encodeURIComponent(SVC_FOO)}`);
    cy.get('[data-test-subj="slosPage"]', { timeout: 30000 }).should('be.visible');
    cy.get('[data-test-subj="activeFilterBadges"]', { timeout: 10000 })
      .should('contain.text', SVC_FOO);
    // Two FOO rows show; the BAR row hides.
    cy.get(`[data-test-subj="slosLink-${created[0]}"]`).should('be.visible');
    cy.get(`[data-test-subj="slosLink-${created[1]}"]`).should('be.visible');
    cy.get(`[data-test-subj="slosLink-${created[2]}"]`).should('not.exist');
  });

  it(`?team= narrows to rows matching that team`, function () {
    if (created.length < 3) {
      this.skip();
      return;
    }
    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos?team=${encodeURIComponent(TEAM_BLUE)}`);
    cy.get('[data-test-subj="slosPage"]', { timeout: 30000 }).should('be.visible');
    cy.get('[data-test-subj="activeFilterBadges"]', { timeout: 10000 })
      .should('contain.text', TEAM_BLUE);
    // Only the BLUE row shows.
    cy.get(`[data-test-subj="slosLink-${created[1]}"]`).should('be.visible');
    cy.get(`[data-test-subj="slosLink-${created[0]}"]`).should('not.exist');
    cy.get(`[data-test-subj="slosLink-${created[2]}"]`).should('not.exist');
  });

  it(`?search= matches a name-token substring`, function () {
    if (created.length < 3) {
      this.skip();
      return;
    }
    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos?search=${tokA}`);
    cy.get('[data-test-subj="slosPage"]', { timeout: 30000 }).should('be.visible');
    cy.get(`[data-test-subj="slosLink-${created[0]}"]`, { timeout: 20000 }).should('be.visible');
    cy.get(`[data-test-subj="slosLink-${created[1]}"]`).should('not.exist');
    cy.get(`[data-test-subj="slosLink-${created[2]}"]`).should('not.exist');
  });

  it(`?search= with no matches surfaces the empty-filtered prompt and clear button`, function () {
    if (created.length < 3) {
      this.skip();
      return;
    }
    // Hyphen-free token so simple_query_string treats it as a single
    // prefix term (hyphens parse as NOT operators in tokenization, which
    // would otherwise pre-filter on a positive token).
    const noMatch = `nosuchtoken${Math.random().toString(36).slice(2, 8)}`;
    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos?search=${encodeURIComponent(noMatch)}`);
    cy.get('[data-test-subj="slosPage"]', { timeout: 30000 }).should('be.visible');
    cy.get('[data-test-subj="slosEmptyFilteredZero"]', { timeout: 15000 }).should('be.visible');
    cy.get('[data-test-subj="slosEmptyFilteredClear"]').click();
    // After clearing, the URL drops the `?service=` param and the seeded
    // rows reappear.
    cy.location('hash', { timeout: 10000 }).should((hash) => {
      expect(hash).to.not.include(noMatch);
    });
    cy.get(`[data-test-subj="slosLink-${created[0]}"]`, { timeout: 15000 }).should('be.visible');
  });
});
