/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/// <reference types="cypress" />

/*
 * SLO multi-workspace isolation.
 *
 * Run locally with:
 *   yarn cypress:run --spec \
 *     .cypress/integration/slo_test/multi_workspace.spec.js \
 *     --env "sloDatasourceId=ObservabilityStack_Prometheus,workspaceId=<seedWs>,opensearchUrl=https://localhost:9200,..."
 *
 * Two workspaces, same Prometheus datasource bound to both. The seed
 * workspace (`Cypress.env('workspaceId')`) is treated as workspace A; a
 * second one is created in `before` for workspace B and torn down in
 * `after`. The Prometheus data-connection from A is associated with B
 * before any SLO creation so SLO POSTs scoped to B can resolve the
 * datasource.
 *
 * What this guards against:
 *
 *   1. SLO created in A is invisible from B's listing & detail page.
 *   2. Same SLI shape in both workspaces produces independent refcounts —
 *      neither shows the "shared with N other SLO" pill, because dedup is
 *      scoped per workspace.
 *   3. Deleting an SLO in A does not alter the SLO in B.
 *   4. Cross-workspace URL: visiting /w/<B>/.../slos/<A's id> in the
 *      browser does not load A's detail; the API call returns 404.
 *
 * Skipped entirely when `Cypress.env('workspaceId')` is unset — CI runs
 * with workspace.enabled=false where these scenarios don't apply.
 */

const APP_ID = 'observability-apm-slo';
const SEED_WORKSPACE_ID = Cypress.env('workspaceId') || null;
const DATASOURCE_ID = Cypress.env('sloDatasourceId') || 'prom_integ_test';

const randomId = (prefix) =>
  `${prefix}-${Math.random().toString(36).slice(2, 8)}-${Date.now().toString(36)}`;

function sloBaseFor(wsId) {
  return wsId ? `/w/${wsId}/api/observability/v1/slos` : `/api/observability/v1/slos`;
}

function appPathFor(wsId, hash) {
  const prefix = wsId ? `/w/${wsId}` : '';
  return `${prefix}/app/${APP_ID}${hash}`;
}

function buildSharedSloSpec(datasourceId, name) {
  return {
    datasourceId,
    name,
    description: 'Cypress multi-workspace spec — autogenerated',
    enabled: true,
    mode: 'active',
    service: 'cypress-mws',
    owner: { teams: ['cypress-team'] },
    sli: {
      type: 'single',
      definition: {
        backend: 'prometheus',
        type: 'availability',
        calcMethod: 'events',
        metric: 'http_requests_total',
        goodEventsFilter: 'status_code!~"5.."',
      },
      dimensions: [{ name: 'service', value: 'cypress-mws' }],
    },
    objectives: [{ name: 'primary', target: 0.99 }],
    budgetWarningThresholds: [],
    window: { type: 'rolling', duration: '28d' },
    alerting: {
      strategy: 'mwmbr',
      burnRates: [
        {
          shortWindow: '5m',
          longWindow: '1h',
          burnRateMultiplier: 14.4,
          severity: 'critical',
          createAlarm: true,
          forDuration: '2m',
        },
      ],
    },
    alarms: {
      sliHealth: { enabled: false },
      attainmentBreach: { enabled: false },
      budgetWarning: { enabled: true },
      noData: { enabled: false, forDuration: '10m' },
      resolved: { enabled: false },
    },
    exclusionWindows: [],
    labels: {},
    annotations: {},
  };
}

(SEED_WORKSPACE_ID ? describe : describe.skip)(
  'SLO multi-workspace isolation',
  () => {
    const nameA = randomId('cypress-mws-a');
    const nameB = randomId('cypress-mws-b');
    let workspaceB = null;
    let dataSourceSavedObjectId = null;
    let dataConnectionSavedObjectIds = [];
    let sloIdA = null;
    let sloIdB = null;

    before(function () {
      if (!SEED_WORKSPACE_ID) {
        this.skip();
        return;
      }

      // Resolve the saved-object IDs for the data-source + data-connection(s)
      // currently bound to workspace A so we can attach the same ones to
      // workspace B. The SLO `datasourceId` field is the connector NAME
      // (e.g. ObservabilityStack_Prometheus); the workspace `settings`
      // payload takes saved-object IDs.
      cy.request({
        method: 'GET',
        url: `/w/${SEED_WORKSPACE_ID}/api/saved_objects/_find?type=data-source&per_page=100`,
        headers: { 'osd-xsrf': 'true' },
        failOnStatusCode: false,
      }).then((resp) => {
        if (resp.status !== 200 || !resp.body || !Array.isArray(resp.body.saved_objects)) return;
        const ds = resp.body.saved_objects[0];
        if (ds) dataSourceSavedObjectId = ds.id;
      });
      cy.request({
        method: 'GET',
        url: `/w/${SEED_WORKSPACE_ID}/api/saved_objects/_find?type=data-connection&per_page=100`,
        headers: { 'osd-xsrf': 'true' },
        failOnStatusCode: false,
      }).then((resp) => {
        if (resp.status !== 200 || !resp.body || !Array.isArray(resp.body.saved_objects)) return;
        dataConnectionSavedObjectIds = resp.body.saved_objects.map((d) => d.id);
      });

      // Create workspace B with the same datasource + connection bindings.
      cy.then(() => {
        const settings = {
          permissions: {
            library_write: { users: ['%me%'] },
            write: { users: ['%me%'] },
          },
          dataSources: dataSourceSavedObjectId ? [dataSourceSavedObjectId] : [],
          dataConnections: dataConnectionSavedObjectIds,
        };
        cy.request({
          method: 'POST',
          url: `/api/workspaces`,
          headers: { 'osd-xsrf': 'true' },
          body: {
            attributes: {
              name: `Cypress SLO B ${Math.random().toString(36).slice(2, 6)}`,
              features: ['use-case-observability'],
              description: 'Cypress multi-workspace spec — workspace B',
            },
            settings,
          },
          failOnStatusCode: false,
        }).then((resp) => {
          if (resp.status === 200 && resp.body && resp.body.success) {
            workspaceB = resp.body.result.id;
          }
        });
      });

      // Create SLO A in workspace A, SLO B in workspace B, both with the
      // same SLI shape so dedup *would* fire if workspaces leaked.
      cy.then(() => {
        if (!workspaceB) return;
        cy.request({
          method: 'POST',
          url: sloBaseFor(SEED_WORKSPACE_ID),
          headers: { 'osd-xsrf': 'true' },
          body: { spec: buildSharedSloSpec(DATASOURCE_ID, nameA) },
          failOnStatusCode: false,
        }).then((resp) => {
          if (resp.status === 200 || resp.status === 201) sloIdA = resp.body.id;
        });
        cy.request({
          method: 'POST',
          url: sloBaseFor(workspaceB),
          headers: { 'osd-xsrf': 'true' },
          body: { spec: buildSharedSloSpec(DATASOURCE_ID, nameB) },
          failOnStatusCode: false,
        }).then((resp) => {
          if (resp.status === 200 || resp.status === 201) sloIdB = resp.body.id;
        });
      });
    });

    after(() => {
      if (sloIdA) {
        cy.request({
          method: 'DELETE',
          url: `${sloBaseFor(SEED_WORKSPACE_ID)}/${encodeURIComponent(sloIdA)}`,
          headers: { 'osd-xsrf': 'true' },
          failOnStatusCode: false,
        });
      }
      if (sloIdB && workspaceB) {
        cy.request({
          method: 'DELETE',
          url: `${sloBaseFor(workspaceB)}/${encodeURIComponent(sloIdB)}`,
          headers: { 'osd-xsrf': 'true' },
          failOnStatusCode: false,
        });
      }
      if (workspaceB) {
        cy.request({
          method: 'DELETE',
          url: `/api/workspaces/${workspaceB}`,
          headers: { 'osd-xsrf': 'true' },
          failOnStatusCode: false,
        });
      }
    });

    it('listing in workspace B does not include workspace A SLOs', function () {
      if (!workspaceB || !sloIdA || !sloIdB) {
        this.skip();
        return;
      }
      cy.request({
        method: 'GET',
        url: `${sloBaseFor(workspaceB)}?pageSize=500`,
        headers: { 'osd-xsrf': 'true' },
        failOnStatusCode: false,
      }).then((resp) => {
        expect(resp.status, `B listing status: ${resp.status}`).to.equal(200);
        // paginate() shapes its response as { results, total, nextCursor,
        // prevCursor } — see common/slo/slo_query_service.ts.
        const ids = (resp.body.results || []).map((it) => it.id);
        expect(ids, 'workspace B listing must not contain SLO A').to.not.include(sloIdA);
        expect(ids, 'workspace B listing must contain SLO B').to.include(sloIdB);
      });
      // UI assertion: visiting B's listing renders a page with B's SLO row
      // present and no row link for A.
      cy.visit(appPathFor(workspaceB, '#/slos'));
      cy.get('[data-test-subj="slosPage"]', { timeout: 30000 }).should('be.visible');
      cy.get(`[data-test-subj="slosLink-${sloIdB}"]`, { timeout: 20000 }).should('be.visible');
      cy.get(`[data-test-subj="slosLink-${sloIdA}"]`).should('not.exist');
    });

    it('same SLI shape in A and B yields independent refcounts (no shared-with pill in either)', function () {
      if (!workspaceB || !sloIdA || !sloIdB) {
        this.skip();
        return;
      }
      // A
      cy.visit(appPathFor(SEED_WORKSPACE_ID, `#/slos/${encodeURIComponent(sloIdA)}`));
      cy.get('[data-test-subj="sloDetailPage"]', { timeout: 30000 }).should('be.visible');
      cy.get('[data-test-subj="slosDetailSharedWithPill"]').should('not.exist');
      // B
      cy.visit(appPathFor(workspaceB, `#/slos/${encodeURIComponent(sloIdB)}`));
      cy.get('[data-test-subj="sloDetailPage"]', { timeout: 30000 }).should('be.visible');
      cy.get('[data-test-subj="slosDetailSharedWithPill"]').should('not.exist');
    });

    it('cross-workspace URL: /w/<B>/slos/<A.id> returns 404 from the API', function () {
      if (!workspaceB || !sloIdA) {
        this.skip();
        return;
      }
      cy.request({
        method: 'GET',
        url: `${sloBaseFor(workspaceB)}/${encodeURIComponent(sloIdA)}`,
        headers: { 'osd-xsrf': 'true' },
        failOnStatusCode: false,
      }).then((resp) => {
        expect(
          resp.status,
          `Expected 404 reading A from B's workspace, got ${resp.status}: ${JSON.stringify(resp.body)}`
        ).to.equal(404);
      });
    });

    it('deleting SLO B does not affect SLO A in workspace A', function () {
      if (!workspaceB || !sloIdA || !sloIdB) {
        this.skip();
        return;
      }
      cy.request({
        method: 'DELETE',
        url: `${sloBaseFor(workspaceB)}/${encodeURIComponent(sloIdB)}`,
        headers: { 'osd-xsrf': 'true' },
        failOnStatusCode: false,
      }).then((resp) => {
        expect(resp.status, `Delete B status: ${resp.status}`).to.be.oneOf([200, 201, 204]);
      });
      // Null out so the after-hook doesn't double-delete.
      sloIdB = null;

      // SLO A is still readable in workspace A.
      cy.request({
        method: 'GET',
        url: `${sloBaseFor(SEED_WORKSPACE_ID)}/${encodeURIComponent(sloIdA)}`,
        headers: { 'osd-xsrf': 'true' },
        failOnStatusCode: false,
      }).then((resp) => {
        expect(resp.status, `Read A after deleting B: ${resp.status}`).to.equal(200);
        expect(resp.body && resp.body.id).to.equal(sloIdA);
      });

      // And A's detail page still loads — no shared-with pill (deleting B
      // can't have changed anything because dedup is per-workspace).
      cy.visit(appPathFor(SEED_WORKSPACE_ID, `#/slos/${encodeURIComponent(sloIdA)}`));
      cy.get('[data-test-subj="sloDetailPage"]', { timeout: 30000 }).should('be.visible');
      cy.get('[data-test-subj="slosDetailSharedWithPill"]').should('not.exist');
    });
  }
);
