/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/// <reference types="cypress" />

/*
 * SLO rule-health recovery flow — real Cortex backend.
 *
 * Run locally with:
 *   yarn cypress:run-without-security --spec \
 *     .cypress/integration/slo_test/rule_health.spec.js
 *
 * Exercises the rule-health detection + recovery UI end-to-end against a real
 * ruler:
 *
 *   1. A healthy SLO shows a "healthy" rule badge on the listing.
 *   2. When the ruler loses the rule group out-of-band, the listing badge
 *      flips to "missing" and the detail page surfaces a red callout with
 *      Restore / Delete buttons.
 *   3. Restore re-asserts the rule group and the callout disappears.
 *   4. Delete-from-callout on a broken SLO confirms and routes back to the
 *      listing.
 *
 * The "out-of-band deletion" — a ruler-level removal that leaves the SLO saved
 * object intact — is produced via `cy.task('cortex:deleteRuleGroup')`. The task
 * issues a direct DELETE against the OS SQL plugin's DirectQuery resource path,
 * bypassing the SLO routes that would otherwise keep the saved object in
 * lockstep with the ruler. Plugin code paths under test are otherwise hit
 * directly with no intercepts.
 *
 * RuleHealthChecker has a TTL so the listing badge doesn't flip immediately;
 * the spec issues `?refresh=true` reads to bypass the cache.
 */

const APP_ID = 'observability-apm-slo';
// Local dev uses workspace.enabled=true and the spec must navigate via
// /w/<id>/app/<id>; CI runs workspace-disabled and uses the bare /app prefix.
// API requests need the same prefix so writes/reads target the same OSD
// workspace as the UI visits.
const WORKSPACE_PREFIX = Cypress.env('workspaceId') ? `/w/${Cypress.env('workspaceId')}` : '';
const SLO_BASE = `${WORKSPACE_PREFIX}/api/observability/v1/slos`;

const randomId = (prefix) =>
  `${prefix}-${Math.random().toString(36).slice(2, 8)}-${Date.now().toString(36)}`;

function buildMinimalSloSpec(datasourceId, name) {
  return {
    datasourceId,
    name,
    description: 'Cypress rule_health spec — autogenerated',
    enabled: true,
    mode: 'active',
    service: 'cypress-svc',
    owner: { teams: ['cypress-team'] },
    sli: {
      type: 'single',
      definition: {
        backend: 'prometheus',
        type: 'availability',
        calcMethod: 'events',
        metric: 'http_requests_total',
        goodEventsFilter: 'status_code!~"5.."',
      },
      dimensions: [{ name: 'service', value: 'cypress-svc' }],
    },
    objectives: [{ name: 'primary', target: 0.99 }],
    budgetWarningThresholds: [],
    window: { type: 'rolling', duration: '28d' },
    alerting: {
      strategy: 'mwmbr',
      burnRates: [
        {
          shortWindow: '5m',
          longWindow: '1h',
          burnRateMultiplier: 14.4,
          severity: 'critical',
          createAlarm: true,
          forDuration: '2m',
        },
      ],
    },
    alarms: {
      sliHealth: { enabled: false },
      attainmentBreach: { enabled: false },
      budgetWarning: { enabled: true },
      noData: { enabled: false, forDuration: '10m' },
      resolved: { enabled: false },
    },
    exclusionWindows: [],
    labels: {},
    annotations: {},
  };
}

describe('SLO rule health — recovery flow (real Cortex)', () => {
  const datasourceId = Cypress.env('sloDatasourceId') || 'prom_integ_test';
  const sloName = randomId('cypress-slo');
  let sloId = null;
  let ruleGroupName = null;
  let rulerNamespace = null;

  before(function () {
    cy.request({
      method: 'POST',
      url: SLO_BASE,
      headers: { 'osd-xsrf': 'true' },
      body: { spec: buildMinimalSloSpec(datasourceId, sloName) },
      failOnStatusCode: false,
    }).then((resp) => {
      // If the datasource isn't ruler-capable in this environment, skip rather
      // than fail — keeps offline-dev runs green.
      if (resp.status !== 200 && resp.status !== 201) {
        Cypress.log({
          name: 'rule_health',
          message: `SLO create failed (status ${resp.status}); skipping spec`,
        });
        this.skip();
        return;
      }
      sloId = resp.body.id;
      const prov = resp.body.status && resp.body.status.provisioning;
      if (!prov || prov.backend !== 'prometheus') {
        Cypress.log({
          name: 'rule_health',
          message: 'SLO created but not ruler-backed; skipping',
        });
        this.skip();
        return;
      }
      // Per-SLO alert group is the simplest target for an out-of-band
      // delete: recording groups are shared by fingerprint, the alert group
      // is owned by exactly this SLO. Deleting it makes rule_health flip
      // to `rules_missing`.
      ruleGroupName = prov.alertGroupName;
      rulerNamespace = prov.rulerNamespace;
      if (!ruleGroupName || !rulerNamespace) {
        Cypress.log({
          name: 'rule_health',
          message: `Provisioning missing alertGroupName or rulerNamespace: ${JSON.stringify(prov)}`,
        });
        this.skip();
      }
    });
  });

  after(() => {
    if (!sloId) return;
    cy.request({
      method: 'DELETE',
      url: `${SLO_BASE}/${encodeURIComponent(sloId)}`,
      headers: { 'osd-xsrf': 'true' },
      failOnStatusCode: false,
    });
  });

  it('surfaces a healthy badge, flips to missing after ruler loss, restores, and lets users delete a broken SLO', () => {
    // -----------------------------------------------------------------------
    // Step A — Baseline: rules exist (badge is healthy or no-data depending
    // on whether the source metric has traffic; CI has neither so it sits at
    // no-data — but crucially NOT 'missing').
    // -----------------------------------------------------------------------
    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos`);
    cy.get('[data-test-subj="slosPage"]', { timeout: 30000 }).should('be.visible');
    cy.get(`[data-test-subj="slosRulesBadge-${sloId}"]`, { timeout: 20000 })
      .should('have.attr', 'data-test-rule-state')
      .and('match', /^(healthy|no-data)$/);

    // -----------------------------------------------------------------------
    // Step B — Out-of-band deletion against the real ruler
    //
    // cy.task hits the SQL plugin's DirectQuery resource path, dropping the
    // rule group server-side without touching the SLO saved object. The
    // listing badge flip is gated by the rule-health checker's 30s TTL —
    // step C waits it out before re-loading.
    // -----------------------------------------------------------------------
    cy.task('cortex:deleteRuleGroup', {
      datasourceId,
      namespace: rulerNamespace,
      groupName: ruleGroupName,
    }).then((res) => {
      if (!res || (res.status >= 400 && res.status !== 404)) {
        throw new Error(`cortex:deleteRuleGroup failed: ${JSON.stringify(res)}`);
      }
    });

    // -----------------------------------------------------------------------
    // Step C — Red badge on the listing
    //
    // The listing badge is driven by the rule-health checker's cache, which
    // has a 30s TTL. Wait it out so the next probe re-checks the ruler and
    // sees the missing rule group.
    // -----------------------------------------------------------------------
    // Two caches in series: rule_health checker (30s TTL) + SLO status
    // service (60s TTL). cy.task bypasses the SLO routes so neither gets
    // invalidate()'d. Wait past both, then explicitly re-fetch via the
    // listing's Refresh button — cy.get retry only re-checks the DOM,
    // React doesn't re-fetch without a navigation or refresh trigger.
    cy.wait(75000);
    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos`);
    cy.get('[data-test-subj="slosPage"]', { timeout: 30000 }).should('be.visible');
    // Loop: click Refresh, give the fetch ~3s, check the badge. Up to 10
    // tries (≈30s of polling) — the cache should expire mid-loop.
    const recheck = (attempt) => {
      if (attempt >= 10) return;
      cy.get('[data-test-subj="slosRefresh"]').click();
      cy.wait(3000);
      cy.get(`[data-test-subj="slosRulesBadge-${sloId}"]`).then(($el) => {
        if ($el.attr('data-test-rule-state') === 'missing') return;
        recheck(attempt + 1);
      });
    };
    recheck(0);
    cy.get(`[data-test-subj="slosRulesBadge-${sloId}"]`)
      .should('have.attr', 'data-test-rule-state', 'missing');

    // -----------------------------------------------------------------------
    // Step D — Restore flow
    // -----------------------------------------------------------------------
    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos/${encodeURIComponent(sloId)}`);
    cy.get('[data-test-subj="sloDetailPage"]', { timeout: 30000 }).should('be.visible');
    cy.get('[data-test-subj="slosDetailRuleHealthCallout"]', { timeout: 20000 }).should(
      'be.visible'
    );

    cy.get('[data-test-subj="slosDetailRestore"]').click();

    // Restore re-asserts the group and the next probe should report 'ok'.
    cy.get('[data-test-subj="slosDetailRuleHealthCallout"]', { timeout: 30000 }).should(
      'not.exist'
    );

    // -----------------------------------------------------------------------
    // Step E — Re-break and delete from the callout
    //
    // Same 30s TTL applies — wait it out before navigating so the detail
    // page's first probe sees the freshly-missing group.
    // -----------------------------------------------------------------------
    cy.task('cortex:deleteRuleGroup', {
      datasourceId,
      namespace: rulerNamespace,
      groupName: ruleGroupName,
    });
    // Same 90s wait so the rule_health/status caches expire before the
    // detail page revisits.
    cy.wait(90000);

    cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos/${encodeURIComponent(sloId)}`);
    cy.get('[data-test-subj="sloDetailPage"]', { timeout: 30000 }).should('be.visible');
    cy.get('[data-test-subj="slosDetailRuleHealthCallout"]', { timeout: 20000 }).should(
      'be.visible'
    );

    cy.get('[data-test-subj="slosDetailBrokenDelete"]').click();
    cy.get('[data-test-subj="slosDetailDeleteModal"]', { timeout: 10000 }).should('be.visible');
    cy.get('[data-test-subj="confirmModalConfirmButton"]').click();

    cy.location('hash', { timeout: 20000 }).should('match', /#\/slos$/);
    cy.get('[data-test-subj="slosPage"]', { timeout: 30000 }).should('be.visible');

    // The SLO is gone (delete-from-callout went through the regular API);
    // null out so `after` doesn't double-DELETE.
    sloId = null;
  });
});
