/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/// <reference types="cypress" />

/*
 * SLO rule-health Phase 1 recovery flow.
 *
 * Run locally with:
 *   yarn cypress:run-without-security --spec \
 *     .cypress/integration/slo_test/rule_health.spec.js
 *
 * This spec exercises the Phase 1 rule-health detection + recovery UI:
 *
 *   1. A healthy SLO shows a "healthy" rule badge on the listing.
 *   2. When the ruler loses the rule group out-of-band, the listing badge
 *      flips to "missing" and the detail page surfaces a red callout with
 *      Restore / Delete buttons.
 *   3. Restore re-asserts the rule group and the callout disappears once
 *      the follow-up rule_health probe reports `state: 'ok'`.
 *   4. Delete-from-callout on a broken SLO confirms and then routes the
 *      user back to the listing.
 *
 * "Out-of-band deletion" — per the Phase 1 plan — is any ruler-level
 * removal of a rule group that leaves the SLO saved object intact. Our
 * SDK doesn't expose a direct-query ruler DELETE without also dropping
 * the saved object, so this spec emulates the desynchronised state via
 * `cy.intercept` on the read paths (list, get, rule_health). The UI
 * contract under test — badge colour, callout presence, button wiring,
 * confirm-modal behaviour — is fully covered by those stubs.
 *
 * The one live API call is creation in `before`; all UI-state-dependent
 * responses are stubbed so the spec is deterministic regardless of the
 * cluster's actual rule evaluation state. Cleanup DELETEs the real SLO
 * via the plugin API in `after`.
 */

const SLO_BASE = '/api/observability/v1/slos';
const APP_ID = 'observability-apm-slo';

// ---------------------------------------------------------------------------
// Fixture builders — inlined per workstream rules (no shared helpers touched)
// ---------------------------------------------------------------------------

const randomId = (prefix) =>
  `${prefix}-${Math.random().toString(36).slice(2, 8)}-${Date.now().toString(36)}`;

function buildMinimalSloSpec(datasourceId, name) {
  return {
    datasourceId,
    name,
    description: 'Cypress rule_health spec — autogenerated',
    enabled: true,
    mode: 'active',
    service: 'cypress-svc',
    owner: { teams: ['cypress-team'] },
    sli: {
      type: 'single',
      definition: {
        backend: 'prometheus',
        type: 'availability',
        calcMethod: 'events',
        metric: 'http_requests_total',
        goodEventsFilter: 'status_code!~"5.."',
      },
      dimensions: [],
    },
    objectives: [
      {
        name: 'primary',
        target: 0.99,
      },
    ],
    budgetWarningThresholds: [],
    window: { type: 'rolling', duration: '28d' },
    alerting: {
      strategy: 'mwmbr',
      burnRates: [
        {
          shortWindow: '5m',
          longWindow: '1h',
          burnRateMultiplier: 14.4,
          severity: 'critical',
          createAlarm: true,
          forDuration: '2m',
        },
      ],
    },
    alarms: {
      sliHealth: { enabled: false },
      attainmentBreach: { enabled: false },
      budgetWarning: { enabled: true },
      noData: { enabled: false, forDuration: '10m' },
      resolved: { enabled: false },
    },
    exclusionWindows: [],
    labels: {},
    annotations: {},
  };
}

/** Minimal summary projection matching SloSummary in common/slo/slo_types.ts. */
function buildSummary({ id, datasourceId, name, state }) {
  return {
    id,
    datasourceId,
    datasourceType: 'prometheus',
    name,
    description: '',
    enabled: true,
    mode: 'active',
    service: 'cypress-svc',
    owner: { teams: ['cypress-team'] },
    sliNodeType: 'single',
    sliBackend: 'prometheus',
    sliLeafType: 'availability',
    dimensions: [],
    objectiveCount: 1,
    worstTarget: 0.99,
    window: { type: 'rolling', duration: '28d' },
    labels: {},
    status: {
      sloId: id,
      objectives: [],
      state,
      firingCount: 0,
      ruleCount: state === 'rules_missing' ? 0 : 3,
      computedAt: new Date().toISOString(),
    },
  };
}

/** Minimal doc + liveStatus projection for GET /slos/{id}. */
function buildDoc({ id, datasourceId, name, ruleGroupName, rulerNamespace, state }) {
  const spec = buildMinimalSloSpec(datasourceId, name);
  return {
    id,
    spec,
    status: {
      version: 1,
      createdAt: new Date().toISOString(),
      createdBy: 'cypress',
      updatedAt: new Date().toISOString(),
      updatedBy: 'cypress',
      provisioning: {
        backend: 'prometheus',
        ruleGroupName,
        rulerNamespace,
        generatedRuleNames: [`${ruleGroupName}:slo:sli_error:ratio_rate5m`],
      },
    },
    liveStatus: {
      sloId: id,
      objectives: [],
      state,
      firingCount: 0,
      ruleCount: state === 'rules_missing' ? 0 : 3,
      computedAt: new Date().toISOString(),
    },
  };
}

function buildRuleHealth({ id, state, ruleGroupName }) {
  const expected = [ruleGroupName];
  if (state === 'ok') {
    return {
      sloId: id,
      state: 'ok',
      expectedGroups: expected,
      presentGroups: expected,
      missingGroups: [],
      computedAt: new Date().toISOString(),
    };
  }
  if (state === 'rules_missing') {
    return {
      sloId: id,
      state: 'rules_missing',
      expectedGroups: expected,
      presentGroups: [],
      missingGroups: expected,
      computedAt: new Date().toISOString(),
    };
  }
  return {
    sloId: id,
    state,
    expectedGroups: expected,
    presentGroups: [],
    missingGroups: expected,
    computedAt: new Date().toISOString(),
  };
}

// ---------------------------------------------------------------------------
// Spec
// ---------------------------------------------------------------------------

describe('SLO rule health — Phase 1 recovery', () => {
  const datasourceId = Cypress.env('sloDatasourceId') || 'prom_integ_test';
  const sloName = randomId('cypress-slo');
  let sloId = null;
  let ruleGroupName = null;
  let rulerNamespace = null;

  before(() => {
    // Create a real SLO. If creation fails (e.g. no ruler-capable datasource
    // in this environment), fall back to a synthetic id so the rest of the
    // spec can still exercise the UI via intercepts.
    cy.request({
      method: 'POST',
      url: SLO_BASE,
      headers: { 'osd-xsrf': 'true' },
      body: { spec: buildMinimalSloSpec(datasourceId, sloName) },
      failOnStatusCode: false,
    }).then((resp) => {
      if (resp.status === 200 || resp.status === 201) {
        sloId = resp.body.id;
        const prov = resp.body.status && resp.body.status.provisioning;
        if (prov && prov.backend === 'prometheus') {
          ruleGroupName = prov.ruleGroupName;
          rulerNamespace = prov.rulerNamespace;
        }
      }
      if (!sloId) {
        // Fallback synthetic state so UI-contract assertions still run.
        sloId = randomId('cypress-slo-id');
        ruleGroupName = `slo_${sloId}_primary`;
        rulerNamespace = 'slos';
      }
    });
  });

  after(() => {
    if (!sloId) return;
    cy.request({
      method: 'DELETE',
      url: `${SLO_BASE}/${encodeURIComponent(sloId)}`,
      headers: { 'osd-xsrf': 'true' },
      failOnStatusCode: false,
    });
  });

  it('surfaces a healthy badge, flips to missing after ruler loss, restores, and lets users delete a broken SLO', () => {
    // -----------------------------------------------------------------------
    // Step A — Healthy baseline
    // -----------------------------------------------------------------------
    cy.intercept('GET', `${SLO_BASE}*`, (req) => {
      // Match the listing endpoint (no trailing id segment).
      if (/\/slos(?:\?|$)/.test(req.url)) {
        req.reply({
          statusCode: 200,
          body: {
            items: [
              buildSummary({ id: sloId, datasourceId, name: sloName, state: 'ok' }),
            ],
            total: 1,
            page: 1,
            pageSize: 25,
          },
        });
      }
    }).as('listHealthy');

    cy.visit(`/app/${APP_ID}#/slos`);
    cy.get('[data-test-subj="slosPage"]', { timeout: 30000 }).should('be.visible');

    cy.get(`[data-test-subj="slosRulesBadge-${sloId}"]`, { timeout: 20000 })
      .should('have.attr', 'data-test-rule-state', 'healthy');

    // -----------------------------------------------------------------------
    // Step B — Out-of-band deletion (simulated via cy.intercept).
    //
    // The plugin's only authoring path for the ruler is wrapped by the
    // SLO routes, which keep the saved object and the rule group in
    // lockstep. A true "operator nuked the rule group behind our back"
    // state is therefore not reachable from a browser without a
    // test-only debug endpoint. We emulate it by swapping the listing
    // and detail responses to describe the desynchronised state — that
    // is exactly the input the Phase 1 UI is designed to react to.
    // -----------------------------------------------------------------------
    cy.intercept('GET', `${SLO_BASE}*`, (req) => {
      if (/\/slos(?:\?|$)/.test(req.url)) {
        req.reply({
          statusCode: 200,
          body: {
            items: [
              buildSummary({
                id: sloId,
                datasourceId,
                name: sloName,
                state: 'rules_missing',
              }),
            ],
            total: 1,
            page: 1,
            pageSize: 25,
          },
        });
      }
    }).as('listMissing');

    cy.intercept('GET', `${SLO_BASE}/${encodeURIComponent(sloId)}`, {
      statusCode: 200,
      body: buildDoc({
        id: sloId,
        datasourceId,
        name: sloName,
        ruleGroupName,
        rulerNamespace,
        state: 'rules_missing',
      }),
    }).as('getBroken');

    cy.intercept('GET', `${SLO_BASE}/${encodeURIComponent(sloId)}/rule_health`, {
      statusCode: 200,
      body: buildRuleHealth({ id: sloId, state: 'rules_missing', ruleGroupName }),
    }).as('ruleHealthMissing');

    // -----------------------------------------------------------------------
    // Step C — Red badge on the listing
    // -----------------------------------------------------------------------
    cy.visit(`/app/${APP_ID}#/slos`);
    cy.get('[data-test-subj="slosPage"]', { timeout: 30000 }).should('be.visible');

    cy.get(`[data-test-subj="slosRulesBadge-${sloId}"]`, { timeout: 20000 })
      .should('have.attr', 'data-test-rule-state', 'missing');

    // -----------------------------------------------------------------------
    // Step D — Restore flow
    // -----------------------------------------------------------------------
    cy.visit(`/app/${APP_ID}#/slos/${encodeURIComponent(sloId)}`);
    cy.get('[data-test-subj="sloDetailPage"]', { timeout: 30000 }).should('be.visible');

    cy.get('[data-test-subj="slosDetailRuleHealthCallout"]', { timeout: 20000 }).should(
      'be.visible'
    );

    // After Restore, the server re-asserts the rule group; stub the
    // follow-up reads to return a healthy state so the callout clears.
    cy.intercept('POST', `${SLO_BASE}/${encodeURIComponent(sloId)}/repair`, {
      statusCode: 200,
      body: {
        sloId,
        repaired: true,
        health: buildRuleHealth({ id: sloId, state: 'ok', ruleGroupName }),
      },
    }).as('repair');

    // Swap the rule_health stub to healthy — any re-probe after repair
    // must see `ok` for the callout to disappear.
    cy.intercept('GET', `${SLO_BASE}/${encodeURIComponent(sloId)}/rule_health`, {
      statusCode: 200,
      body: buildRuleHealth({ id: sloId, state: 'ok', ruleGroupName }),
    }).as('ruleHealthOk');

    cy.intercept('GET', `${SLO_BASE}/${encodeURIComponent(sloId)}`, {
      statusCode: 200,
      body: buildDoc({
        id: sloId,
        datasourceId,
        name: sloName,
        ruleGroupName,
        rulerNamespace,
        state: 'ok',
      }),
    }).as('getHealthy');

    cy.get('[data-test-subj="slosDetailRestore"]').click();
    cy.wait('@repair');

    cy.get('[data-test-subj="slosDetailRuleHealthCallout"]', { timeout: 20000 }).should(
      'not.exist'
    );

    // -----------------------------------------------------------------------
    // Step E — Delete a broken SLO from the callout
    //
    // Re-break the state so the callout is present, then click
    // slosDetailBrokenDelete, confirm, and assert the app routes back
    // to the listing.
    // -----------------------------------------------------------------------
    cy.intercept('GET', `${SLO_BASE}/${encodeURIComponent(sloId)}`, {
      statusCode: 200,
      body: buildDoc({
        id: sloId,
        datasourceId,
        name: sloName,
        ruleGroupName,
        rulerNamespace,
        state: 'rules_missing',
      }),
    }).as('getBrokenAgain');

    cy.intercept('GET', `${SLO_BASE}/${encodeURIComponent(sloId)}/rule_health`, {
      statusCode: 200,
      body: buildRuleHealth({ id: sloId, state: 'rules_missing', ruleGroupName }),
    }).as('ruleHealthMissingAgain');

    cy.intercept('DELETE', `${SLO_BASE}/${encodeURIComponent(sloId)}`, {
      statusCode: 200,
      body: { deleted: true, generatedRuleNames: [] },
    }).as('deleteBroken');

    cy.visit(`/app/${APP_ID}#/slos/${encodeURIComponent(sloId)}`);
    cy.get('[data-test-subj="sloDetailPage"]', { timeout: 30000 }).should('be.visible');
    cy.get('[data-test-subj="slosDetailRuleHealthCallout"]', { timeout: 20000 }).should(
      'be.visible'
    );

    cy.get('[data-test-subj="slosDetailBrokenDelete"]').click();

    // Confirm modal — title includes "Delete SLO".
    cy.get('.euiModal', { timeout: 10000 }).should('be.visible');
    cy.contains('.euiModalHeader', 'Delete SLO').should('be.visible');

    // Click the danger confirm button in the modal footer.
    cy.get('.euiModalFooter').find('button.euiButton--danger').click();

    cy.wait('@deleteBroken');

    // After delete we expect to land back on the listing route.
    cy.location('hash', { timeout: 20000 }).should('match', /#\/slos$/);
    cy.get('[data-test-subj="slosPage"]', { timeout: 30000 }).should('be.visible');
  });
});
