/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/// <reference types="cypress" />

/*
 * SLO wizard — non-custom templates.
 *
 * Run locally with:
 *   yarn cypress:run --spec \
 *     .cypress/integration/slo_test/wizard_templates.spec.js \
 *     --env "sloDatasourceId=ObservabilityStack_Prometheus[,workspaceId=<id>]"
 *
 * The wizard exposes 12 templates (custom plus 11 specialized). Custom is
 * exercised by slo_crud_smoke and wizard_validation; this spec confirms the
 * non-custom path:
 *
 *   1. Each template tile is clickable and lands on the wizard form.
 *   2. APM-derived templates pre-fill the custom PromQL editor with a
 *      goodQuery and totalQuery.
 *   3. OTel HTTP availability / latency templates render the metric +
 *      goodEventsFilter fields with sensible defaults.
 *   4. Server-side accepts representative non-custom shapes when posted
 *      via API (independent of any template-specific UI flow).
 *
 * Each shape we POST is constructed from scratch to sidestep wizard
 * mechanics — the wizard's job is to produce a valid spec, and these
 * tests confirm representative validated specs are still accepted by the
 * route.
 */

const APP_ID = 'observability-apm-slo';
const WORKSPACE_PREFIX = Cypress.env('workspaceId') ? `/w/${Cypress.env('workspaceId')}` : '';
const SLO_BASE = `${WORKSPACE_PREFIX}/api/observability/v1/slos`;

const randomId = (prefix) =>
  `${prefix}-${Math.random().toString(36).slice(2, 8)}-${Date.now().toString(36)}`;

function visitPicker() {
  cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos`);
  cy.get('[data-test-subj="slosPage"]', { timeout: 30000 }).should('be.visible');
  cy.visit(`${WORKSPACE_PREFIX}/app/${APP_ID}#/slos/create`);
}

function commonScaffold(datasourceId, name, sliOverrides, objectives = [{ name: 'primary', target: 0.99 }]) {
  return {
    datasourceId,
    name,
    description: 'Cypress wizard_templates spec — autogenerated',
    enabled: true,
    mode: 'active',
    service: 'cypress-svc',
    owner: { teams: ['cypress-team'] },
    sli: sliOverrides,
    objectives,
    budgetWarningThresholds: [],
    window: { type: 'rolling', duration: '28d' },
    alerting: {
      strategy: 'mwmbr',
      burnRates: [
        {
          shortWindow: '5m',
          longWindow: '1h',
          burnRateMultiplier: 14.4,
          severity: 'critical',
          createAlarm: true,
          forDuration: '2m',
        },
      ],
    },
    alarms: {
      sliHealth: { enabled: false },
      attainmentBreach: { enabled: false },
      budgetWarning: { enabled: true },
      noData: { enabled: false, forDuration: '10m' },
      resolved: { enabled: false },
    },
    exclusionWindows: [],
    labels: {},
    annotations: {},
  };
}

describe('SLO wizard — template picker + non-custom shapes', () => {
  const datasourceId = Cypress.env('sloDatasourceId') || 'prom_integ_test';
  const created = [];

  after(() => {
    created.forEach((id) => {
      cy.request({
        method: 'DELETE',
        url: `${SLO_BASE}/${encodeURIComponent(id)}`,
        headers: { 'osd-xsrf': 'true' },
        failOnStatusCode: false,
      });
    });
  });

  it('picker renders all 12 templates and each tile is clickable', () => {
    visitPicker();
    const templateIds = [
      'apm-service-availability',
      'apm-service-latency',
      'apm-dependency-availability',
      'apm-dependency-latency',
      'http-availability',
      'http-latency',
      'rpc-availability',
      'rpc-latency',
      'db-client-latency',
      'messaging-latency',
      'genai-availability',
      'custom',
    ];
    templateIds.forEach((id) => {
      cy.get(`[data-test-subj="slosTemplate-${id}"]`, { timeout: 20000 }).should('be.visible');
    });
  });

  it('apm-service-availability picker → wizard pre-fills custom PromQL editor', () => {
    visitPicker();
    cy.get('[data-test-subj="slosTemplate-apm-service-availability"]', { timeout: 20000 }).click();
    cy.get('[data-test-subj="sloWizardPage"]', { timeout: 20000 }).should('be.visible');
    cy.get('[data-test-subj="slosWizardCustomPromqlGood"]', { timeout: 10000 })
      .invoke('val')
      .should((value) => {
        expect(value, `custom good query auto-fill: ${value}`).to.match(/.+/);
      });
    cy.get('[data-test-subj="slosWizardCustomPromqlTotal"]')
      .invoke('val')
      .should((value) => {
        expect(value, `custom total query auto-fill: ${value}`).to.match(/.+/);
      });
  });

  it('http-availability picker → wizard renders metric and goodEventsFilter fields', () => {
    visitPicker();
    cy.get('[data-test-subj="slosTemplate-http-availability"]', { timeout: 20000 }).click();
    cy.get('[data-test-subj="sloWizardPage"]', { timeout: 20000 }).should('be.visible');
    // For availability templates the wizard surfaces the goodEventsFilter
    // form row, pre-filled with the template default.
    cy.get('[data-test-subj="slosWizardGoodEventsFilter"]')
      .invoke('val')
      .should((value) => {
        expect(value, `goodEventsFilter default: ${value}`).to.match(/http_response_status_code/);
      });
  });

  it('server accepts an availability shape (http-availability template) via API', () => {
    const name = randomId('cypress-tmpl-http-avail');
    cy.request({
      method: 'POST',
      url: SLO_BASE,
      headers: { 'osd-xsrf': 'true' },
      body: {
        spec: commonScaffold(datasourceId, name, {
          type: 'single',
          definition: {
            backend: 'prometheus',
            type: 'availability',
            calcMethod: 'events',
            metric: 'http_server_request_duration_seconds_count',
            goodEventsFilter: 'http_response_status_code!~"5.."',
          },
          dimensions: [{ name: 'service_name', value: 'cypress-svc' }],
        }),
      },
      failOnStatusCode: false,
    }).then((resp) => {
      expect(resp.status, `http-avail POST: ${JSON.stringify(resp.body)}`).to.be.oneOf([200, 201]);
      created.push(resp.body.id);
    });
  });

  it('server accepts a latency_threshold shape (http-latency template) via API', () => {
    const name = randomId('cypress-tmpl-http-lat');
    cy.request({
      method: 'POST',
      url: SLO_BASE,
      headers: { 'osd-xsrf': 'true' },
      body: {
        spec: commonScaffold(
          datasourceId,
          name,
          {
            type: 'single',
            definition: {
              backend: 'prometheus',
              type: 'latency_threshold',
              calcMethod: 'events',
              metric: 'http_server_request_duration_seconds_bucket',
              latencyThresholdUnit: 'seconds',
            },
            dimensions: [{ name: 'service_name', value: 'cypress-svc' }],
          },
          [{ name: 'primary', target: 0.99, latencyThreshold: 0.5 }]
        ),
      },
      failOnStatusCode: false,
    }).then((resp) => {
      expect(resp.status, `http-lat POST: ${JSON.stringify(resp.body)}`).to.be.oneOf([200, 201]);
      created.push(resp.body.id);
    });
  });

  it('server accepts a custom-PromQL shape (apm-service template) via API', () => {
    const name = randomId('cypress-tmpl-apm');
    cy.request({
      method: 'POST',
      url: SLO_BASE,
      headers: { 'osd-xsrf': 'true' },
      body: {
        spec: commonScaffold(datasourceId, name, {
          type: 'single',
          definition: {
            backend: 'prometheus',
            type: 'custom',
            calcMethod: 'events',
            customExpr: {
              mode: 'events',
              goodQuery: 'sum(rate(span_request_total{service="cypress-svc"}[5m]))',
              totalQuery: 'sum(rate(span_request_total{service="cypress-svc"}[5m]))',
            },
          },
          dimensions: [],
        }),
      },
      failOnStatusCode: false,
    }).then((resp) => {
      expect(resp.status, `apm POST: ${JSON.stringify(resp.body)}`).to.be.oneOf([200, 201]);
      created.push(resp.body.id);
    });
  });
});
